### ISSUE TITLE
Breaking behavior when UntypedObject is used as a return type of a custom function

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#1001]
Related to https://github.com/microsoft/Power-Fx/issues/999

We have a custom function that returns FormulaType.UntypedObject

```csharp
public class MyCustom2Function : ReflectionFunction
    {
        public MyCustom2Function() : base("MyCustom2", FormulaType.UntypedObject, FormulaType.String, FormulaType.String) { ... }

        public virtual FormulaValue Execute(StringValue arg1, StringValue arg2) { ... }
    }
```

For the untyped object, we wrote our own custom class like the following:

```csharp

    public class WrapperUntypedObject : IUntypedObject
    {
        public FormulaType ActualType { get; private set; }

        public FormulaType Type => ActualType;

        public WrapperUntypedObject(FormulaValue realFormulaValue)
        {
            ActualType = realFormulaValue.Type;
        }
       ...
    }
```

Now, with the addition of the new error handling, 
https://github.com/microsoft/Power-Fx/blob/85a2baf0a4cf732da5a9d08d933c15c505b41808/src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs#L416-L421

Our scenarios are failing because our `WrapperUntypedObject.Type` isn't `FormulaType.UntypedObject`.

Is this new behavior intentional? We'd like the original behavior if possible :)

**Comment by jas-valgotar** [comment]
Hi @susosuso,

Can you elaborate on what is the execute method returning? I can't see that in the snippet.

I assume it would be returning the `UntypedObjectValue`.
And while creating that `UntypedObjectValue` you would pass in an `IRContext` instance as a 1st argument, I believe that IRContext should have `ResultType` as `UntypedObject`. If that's the case I would have to investigate it more in detail.

So, `Execute` method could be returning something similar to below snippet,
`return new UntypedObjectValue(IRContext.NotInSource(FormulaType.UntypedObject), new WrapperUntypedObject(formulaValue));`

**Comment by susosuso** [comment]
We don't have access to IRContext. Instead we call `FormulaValue.New(IUntypedObject)`
https://github.com/microsoft/Power-Fx/blob/cc8c619d248e6aebb86bbee65e15bc6bee7f8e88/src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs#L125

Our `Execute` does return UntypedObjectValue as you assumed. Here's a simplified version of our function:
```csharp
        public virtual FormulaValue Execute(StringValue arg1)
        {
            FormulaValue innerFormulaValue = FormulaValue.New(20); // In our actual function, this doesn't have to number. It Can be any type.
 
            return FormulaValue.New(new WrapperUntypedObject(innerFormulaValue));
        }
```

Then if we execute 
`MyCustom2("blah")`
we get the error:
`Error Return type should have been O, found n`

Back in `ReflectionFunction.cs` in my original post -- I think `IRContext.ResultType` is `UntypedObject` as expected there. But `WrapperUntypedObject.Type` determines what `formulaResult.Type` is, and it is the value of the "inner" type of the `WrapperUntypedObject`

**Comment by jas-valgotar** [comment]
@susosuso Thanks for the more details. Oh yes, you are correct you must be using `FormulaValue.New(IUntypedObject)`.

With the given snippet I am unable to reproduce the issue.

I believe `formulaResult.Type` should be the type of `UntypedObjectValue.Type` which should have been `UntypedObject`.
https://github.com/microsoft/Power-Fx/blob/cc8c619d248e6aebb86bbee65e15bc6bee7f8e88/src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs#L128

Maybe there is a code path that doesn't use the `FormulaValue.New(IUntypedObject)` and directly returns `WrapperUntypedObject` instance? If that's not the case, feel free to ping me on teams and we can jump on a quick call so I can reproduce the issue! 

I am using below snippets for the test:
```csharp
        public class MyCustom2Function : ReflectionFunction
        {
            public MyCustom2Function()
                : base("MyCustom2", FormulaType.UntypedObject, FormulaType.String, FormulaType.String) 
            {
            }

            public static FormulaValue Execute(StringValue arg1, StringValue arg2) 
            {
                FormulaValue innerFormulaValue = FormulaValue.New(20); // In our actual function, this doesn't have to number. It Can be any type.

                return FormulaValue.New(new TestWrapperUntypedObject(innerFormulaValue));
            }
        }

        private class TestWrapperUntypedObject : IUntypedObject
        {
            public FormulaType ActualType { get; private set; }

            public FormulaType Type => ActualType;

#pragma warning disable CA1065 // Do not raise exceptions in unexpected locations
            public IUntypedObject this[int index] => throw new IndexOutOfRangeException();
#pragma warning restore CA1065 // Do not raise exceptions in unexpected locations

            public TestWrapperUntypedObject(FormulaValue realFormulaValue)
            {
                ActualType = realFormulaValue.Type;
            }

            public int GetArrayLength()
            {
                throw new NotImplementedException();
            }

            public bool TryGetProperty(string value, out IUntypedObject result)
            {
                throw new NotImplementedException();
            }

            public string GetString()
            {
                throw new NotImplementedException();
            }

            public double GetDouble()
            {
                throw new NotImplementedException();
            }

            public bool GetBoolean()
            {
                throw new NotImplementedException();
            }
        }

        [Fact]
        public void MyCustomFunctionTest()
        {
            var config = new PowerFxConfig(null);
            config.AddFunction(new MyCustom2Function());
            var engine = new RecalcEngine(config);

            // Shows up in enuemeration
            var func = engine.GetAllFunctionNames().First(name => name == "MyCustom2");
            Assert.NotNull(func);

            // Can be invoked. 
            var result = engine.Eval("MyCustom2(\"a\", \"b\")");
            Assert.IsType<UntypedObjectValue>(result);
        }
```

**Comment by susosuso** [comment]
Hi @jas-valgotar I see where my tests failed. I simplified the code out, but our code to create new `UntypedObjectValue` is actually this:

```csharp
        public static FormulaValue New(FormulaValue innerFormulaValue)
        {
            if (innerFormulaValue is BlankValue blank)
            {
                return blank;
            }
            else if (innerFormulaValue is ErrorValue error)
            {
                return error;
            }

            return FormulaValue.New(new WrapperUntypedObject(innerFormulaValue));
        }
```

And all my failures are when the value is BlankValue or ErrorValue 😅. From your answer in #999, the below fixes my problem 😊

```csharp
        public static FormulaValue New(FormulaValue innerFormulaValue)
        {
            if (innerFormulaValue is BlankValue)
            {
                return FormulaValue.NewBlank(FormulaType.UntypedObject);
            }
            else if (innerFormulaValue is ErrorValue error)
            {
                return FormulaValue.NewError(error.Errors.First(), FormulaType.UntypedObject);
            }

            return FormulaValue.New(new WrapperUntypedObject(innerFormulaValue));
        }
```

But now I have one request -- For returning `ErrorValue`, I'd like to return all the original errors. 
`ErrorValue.Errors` is `IReadOnlyList<ExpressionError>`
But we can only pass in one `ExpressionError` via `FormulaValue.NewError(ExpressionError error, FormulaType type)` 

Thank you 😊

**Comment by jas-valgotar** [comment]
I have added the new convenient method you requested. https://github.com/microsoft/Power-Fx/pull/1022

FYI, https://github.com/microsoft/Power-Fx/pull/1018
Now, whenever you just want to give an error message you can just throw the `CustomFunctionErrorException` and we will catch that and wrap it into the proper type ErrorValue. :)

**Comment by susosuso** [comment]
Great! Thank you for such speedy responses and the new method! :)
