### ISSUE TITLE
Consider moving the blank value handling of function parameters to the IR

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1006]
Power Fx has clear rules of how blank values should be handled: if passed to functions in a parameter where a string value is expected, it should be interpreted as an empty string; for numeric parameters, it should be interpreted as 0; false for Boolean values, and the "date 0" for date, time or date/time arguments. Since this is a common rule, we should implement this logic in the IR so that different platforms don't have to implement it themselves.

**Comment by MikeStall** [comment]
See #820 - hat starts this work. 

See 'replaceBlankValues' in  [Library.cs ](https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs)  for inspiration. .
Right idea, but that's all Interpreter-specific, so not part of IR.  

This is most interesting for the subset of functions implemented by SQL backend. 

That has several "trivial" modes:
- DoNotReplaceBlank 
- ReplaceBlankWithZero - 40 usages
- ReplaceBlankWithEmptyString - 13 usages 
as well as some more complex ones 

1. Add a virtual onto TexlFunction to capture BlankHandling semantics
2. IR can read and handle this. 
3. Remove all "trivial blank" handling from Library.cs and leverage IR.  (effectively, a replace their blankHandler with "NopAlreadyHandledByIR" handler that is just a nop)
