### ISSUE TITLE
Consider implementing the coercion from string to Boolean values in the IR

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1007]
Power Fx has clear rules of how string values are coerced to strings:

- "true" maps to true (case insensitive, so "TRUE" and "True" would behave the same)
- "false" maps to false (case insensitive, so "FaLsE" and "FALse" would behave the same)
- "" and blank values maps to Blank
- Everything else is an error

Since this is a common rule, we should implement this logic in the IR so that different platforms don't have to implement it themselves.

**Comment by MikeStall** [comment]
IR already handles this ... this may be an issue in the backends.

**Comment by MikeStall** [comment]
This has been fixed.
