### ISSUE TITLE
Pretty Print null ref when Table has Blank() as one of the row.

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#1028]
Pretty Print Gives null ref when Table has Blank() as one of the rows.

The below expression should run successfully.
e.g.
`Table(Blank())`
`Table({a:1, b:2}, Blank())`
`Table(Blank(), {a:1, b:2})`

**Comment by MikeStall** [comment]
You can test this by running the expressions in the repl.

**Comment by nguhoa** [comment]
Fixed by: https://github.com/microsoft/Power-Fx/pull/1030
