### ISSUE TITLE
Large named formula code causing error and freezing for custom page

### ISSUE THREAD

**Issue by kayetter** [microsoft/Power-Fx#1043]
I am building a complicated custom page for my model driven app. I am following the advice from MS here [Build large and complex canvas apps - Power Apps | Microsoft Learn](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-large-apps) where there is a whole section called 'Use named formulas everywhere'. I have tried to build a lot of logic in the formulas but now my whole app is crashing when I try to make the smallest change to the formula code. The crash looks something like below screenshot with the breadcrumb spinner continuously running on the top of the page. The only way to resolve is to refresh the app. If I look at my code in vscode it is about 347 lines. I am kind of stuck now because everything I do causes this crash.

![image](https://user-images.githubusercontent.com/22959546/215510615-93666477-fd8a-42a7-a369-86186869c9e5.png)

Is there a limit to the amount of logic here or is there something particular that might cause the crash?

**Comment by VamsiModem** [comment]
Hello @kayetter, thanks for reporting the crash, there is no limit on the amount of logic. We will need more details to investigate what's happening here, could you please send a sample app to vmodem@microsoft.com?

**Comment by kayetter** [comment]
This is a custom page in model driven app. I could send you the solution but it is rather large and would require data. Do you want access to a dev environment where I have this solution installed?

**Comment by kayetter** [comment]
but then again, maybe you could just open the custom page and work with it without data. That might work

**Comment by VamsiModem** [comment]
I see, I would really appreciate, if you can provide a simple app with a repro of this issue which will speed up the investigation, for data sources, I can create dummy tables with same schema, if am I unable to do this, I will reach out to you for more details.

**Comment by kayetter** [comment]
Let me see what I can do. I don't know if it is the same behavior in a regular canvas app so I will have to make you a smaller version of the model driven app without dependencies on the PowerCat Creator kit.

**Comment by VamsiModem** [comment]
That would be great, Thanks!

**Comment by VamsiModem** [comment]
I wasn't able to repro this issue locally also there are no new reports of this issue, hence closing it.
