### ISSUE TITLE
Type coercion in host

### ISSUE THREAD

**Issue by babrekel** [microsoft/Power-Fx#1045]
Power FX is able to convert various values between types. Examples:

```
Value("5") -> 5
Value("true") -> Error
Boolean(1) -> true
Boolean(0) -> false
Boolean(100) -> true
Boolean("yes") -> Error
Boolean("true") -> true
// And so forth...
``` 

Working with external data is a common paradigm for users of PVA. This includes parsing API responses from HTTP calls, parsing custom events / messages sent from the client, etc. Users of PVA can leverage the "Parse Value" node to select a type from Sample Data and convert an `UntypedObject` or `String` value to the target type.

To make this scenario work, a host API is requested to do appropriate conversions to the desired type. For example, if I have a `FormulaValue` that represents the number `1`, and the desired `FormulaType` is `Boolean`, the output would be `true`. Potential method signature:

```
FormulaValue TryCoerceTo(FormulaValue input, FormulaType targetType);
```

This can be used in data connectors to process things like `DateTime` from API responses.

**Comment by MikeStall** [comment]
Some more notes:
1. This is just a hosting API and has no impact on language semantics
2. This should work recursively with records.  Errors are granular per-field. 
3.  This should just call existing ctor functions. So BooleanType calls Boolean() function, Numbertype calls Value() function
4.  Can we make this consistent with the coercion rules for untyped object.

**Comment by nguhoa** [comment]
Issue is fixed in https://github.com/microsoft/Power-Fx/pull/1062
