### ISSUE TITLE
Data types coercion for GUID

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#1052]
The following works in PA but gives a runtime error in C# interpreter:
`Upper(GUID("2f8f55fb-4009-4cb6-82aa-4135dbb7244c"))`

https://github.com/microsoft/Power-Fx/blob/2ee0b4896d8f0750fab9924205030337b57dd093/src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs#L968

`expetedType` accepts the coercion but doesn't give the change to set `coercionType` with the destination type.

**Comment by MikeStall** [comment]
Mitigated with #1150, moving to 1.1.

**Comment by CarlosFigueiraMSFT** [comment]
This was fixed with #1281
