### ISSUE TITLE
Text() function when used with DateTime(), Date(), Time() functions, is not identical to PowerApps. 

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#1054]
Below Expressions should evaluate correctly as shown.

`Text(DateTime(2023,1,1,0,0,0))` => `1/1/2023 12:00 AM`
`Text(Date(2023,1,1))` => `1/1/2023`
`Text(Time(2,1,1))` => `2:01 am`

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1061
