### ISSUE TITLE
Ability to access id from optionsets

### ISSUE THREAD

**Issue by sbacha** [microsoft/Power-Fx#1091]
We have an ask to support exposing the id from optionsets for multi-language scenarios where a customer is calling an api with the optionset as a parameter. Having access to the id will render the api consistant across all locales.

**Comment by MikeStall** [comment]
Note that Text() will return the DisplayName. 
They want a way to get logical id.

**Comment by MikeStall** [comment]
`Text(opt)` already returns the display name, and we can't change that. 
So we need a new function. `OptionSetInfo(opt)`, which accepts any option set and returns the string. 
See if we can implement this exclusively in the IR. 

Notes from McCall:

Basically, we need a function F(OptionSetValue): BackingType, where BackingType == String | Number | Boolean | Color, known statically at compile time. 
We have the type and runtime info available to do this, we'd just need a name for it. 
it'd return the backing scalar value, whatever that is (logical name, int id for Dataverse option sets, boolean for Dataverse 2-option, ...)

For the all-possible-values scenario, we already have the Choices(OptionSet): *[Value: OptionSetValue] function in canvas for that, and I think we may just not have impled it yet in C#.
