### ISSUE TITLE
Intellisense information for custom functions

### ISSUE THREAD

**Issue by eswarpr** [microsoft/Power-Fx#1097]
Hi,

Is there anyway to provide additional intellisense information for custom functions I am writing? At present it is simply suggesting generic names like "Arg 1" in the formula bar.

Regards & thanks,
Eswar

**Comment by MikeStall** [comment]
Currently, no. 
What additional information would you like to show up?

**Comment by eswarpr** [comment]
Hi @MikeStall. So, what I am doing is trying to implement a custom function based on reflection function and trying to use it in a formula. I have the language server APIs created, and have a page with [@microsoft/power-fx-formulabar](https://www.npmjs.com/package/@microsoft/power-fx-formulabar) component configured. It is all working fine when I use a built-in function like below

![image](https://user-images.githubusercontent.com/3127176/219593273-cc7cff24-fcef-4840-b991-17384e3cfc83.png)

But when I try my custom function in the formula bar, I get this

![Custom](https://user-images.githubusercontent.com/3127176/219593431-d7414ee7-2d79-42d6-b565-1469dd05a986.png)

I am hoping that I can provide function description, and description and name for parameters somewhere in my function definition or config, so I can get intellisense like the built-in functions, for my custom function.

Possible?

**Comment by jas-valgotar** [comment]
This is fixed via https://github.com/microsoft/Power-Fx/pull/1774

**Comment by eswarpr** [comment]
Many thanks @jas-valgotar
