### ISSUE TITLE
Operators and separators shouldn't be region dependent

### ISSUE THREAD

**Issue by hellbound22** [microsoft/Power-Fx#11]
I wrote a whole rant on some things that I didn't like in Power Apps in dev.to. But I'll try to keep it civil here.

https://github.com/microsoft/Power-Fx/blob/main/docs/global.md#formula-separators-and-chaining-operator this makes no sense.

1 - It fools seasoned programmers and our conventions
2 - it fools newcomers in thinking that ye old copy/paste from the internet solution will work for them, making forums less useful and friendly
3 - Its not "Think Excel". Excel lets you change separators independent of where you are in the world.
4 - In some regions, it just makes the code look ugly (eg.: ```;;```)
5 - Documentation in docs.microsoft.com is not localized (yet). This creates confusion.

One solution is to get rid of this localization system all together and follow a nice standard.
The other is to see follow item 3 and just let developers choose what format to use.

**Comment by MikeStall** [comment]
We are effectively doing #3 -  at the SDK level, this is controlled based on the locale you pass into the parser options. So a host can choose to run everything in en-US (regardless of where it is actually running).
