### ISSUE TITLE
Fluent UI Combo Box doesn't expose Search Text property

### ISSUE THREAD

**Issue by ChrispyBites** [microsoft/Power-Fx#1103]
I'm not sure if this is the right repo to post this in or not, but I can't seem to find one more closely aligned.  The modern, Fluent UI combo box control you can add in PowerApps component libraries doesn't seem to have the Search Text property exposed in the way that the original Combo Box does.  It doesn't appear to be referenceable in anyway.

For example. if I wanted to create a component that serves up a people picker field and used, as input for the component, the Office365Users.SearchUserV2 method, the combobox in the component set to allow searching isn't emitting the text that's typed into the component in any way.

**Comment by MikeStall** [comment]
This repo is for developers consuming the Power Fx engine. 

For your question about Fluent, can you ask it on this form here:

https://powerusers.microsoft.com/t5/Building-Power-Apps/bd-p/PowerAppsForum1

**Comment by ChrispyBites** [comment]
Thanks, @MikeStall!
