### ISSUE TITLE
Culture: Text formatting of dates isn't using localized names

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1105]
Consider 
`Text(Today(), DateTimeFormat.LongDate, "fr-FR")`

In RecalcEngine, we return with English names:
`"Thursday, 23 February 2023"`

In PowerApps, we return with french names:
![image](https://user-images.githubusercontent.com/1538900/220799690-0c071dfc-49d8-4425-83d6-286d2e2f4dae.png)

**Comment by MikeStall** [comment]
We should also verify this parses. 
DateValue(str, "fr-FR"), DateTimeValue(str, "fr-FR")

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1119
