### ISSUE TITLE
Expose User host object

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1114]
Power Apps has existing user function:  https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-user

The schema here includes: Email, FullName, and Image. 

This should be in Power Fx Core so that other hosts can access in a consistent way.  

There's an existing UserFunction definition in PowerApps (USer.cs) that should just be moved to core.  

**For interpreter**, 
- hosts can provide the values via a ServiceProvider. 
- We have tests that demonstrate this: https://github.com/microsoft/Power-Fx/blob/76508caefa6f2c4deece9d3eded53ced7071583d/src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs#L662 . But note that the test example derives from CustomFunction, whereas we should just use the definition from PAclient in User.cs.
- if the User value is not set, then function can fail. 
- we may need to allow it to be a **lazy lookup** to get email/name. Sometimes the host just has a user guid, and getting name,email requires a network call. 

TBD on how to handle Image.

**Comment by MikeStall** [comment]
fyi,  PowerApps impl of Email has some issues: https://github.com/MicrosoftDocs/powerapps-docs/issues/3152

**Comment by MikeStall** [comment]
Adding Needs Discussion tag, cc @jorisdg

**Comment by MikeStall** [comment]
Upon discussion with @gregli-msft, @jorisdg , @Shpakh-MSFT , we decided on:

1. User object, not User() function. This is more consistent with other host-level objects.  This is a known divergence from PowerApps, but we will update Power Apps.
2. But still same fields (full name, email, image)
3. Still add some hosting API to allow hosts to specify the fields

In case of conflict between a local symbol and the builtin global, not that Power Fx allows [@identifier] to refer to global namespace.  We can double check that Intellisense shows both [@User] and User if there is a conflict.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1214
