### ISSUE TITLE
Add helper to determine if type can be coerced to Text

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1127]
Host will call Text() (see #1126) to convert to string, but wants to know if text would accept the given type. 

At editor time, they could call this from #1125. 

The recent TryCoercionProvider.ToString helps for runtime values, but we want this on formula types.
https://github.com/microsoft/Power-Fx/blob/9178b974eced29fd06030d0f3ec563fa0048cf74/src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs#L46

**Comment by nguhoa** [comment]
Fixed in PR: https://github.com/microsoft/Power-Fx/pull/1134
