### ISSUE TITLE
Missing support for function Language()

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#1128]
Power Fx library should support the `Language()` function which returns the default locale set at runtime.

**Comment by MikeStall** [comment]
https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-language

This should get the "current culture" specified to the eval (in the same way that Text() does)  and return the culture string. 
The eval is provided by the host and ends up in the Eval's ServiceProvider

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1147
