### ISSUE TITLE
RecordValue.NewRecordFromFields enumerating twice 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1141]
`NewRecordFromFields(IEnumerable<NamedValue> fields)` is traversing enumeration twice:

1. To scan through and build up the RecordType signature
2. to construct the InMemoryRecordValue

We should only traverse it once. 

- If the implementation really needs to traverse twice, then it should call ToArray() (1 traversal) and then use that. 
- Should add a regression test to confirm it's only traversed once. 
-

**Comment by MikeStall** [comment]
(hitting this with dataverse marshalling)

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1154
