### ISSUE TITLE
Language() default should not be ""

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1195]
By default, our engine has invariant culture, but 
`CultureInfo.InvariantCulture.Name // “”`

So Language() in Fx is returning "" in default cases (when culture is not set). 

However:
1. for resource localization, invariant culture uses "en-US". 
2. By default, in PowerApps,  Language() returns "en-US", not "".

So Fx should do the same.  For invariant / null culture, return "en-US". 

We do have a test, but it sets the culture in base class, so doesn't really test it. 
https://github.com/microsoft/Power-Fx/blob/2cace9a65b3a98e792ba0072cd2a2a4c9d27d191/src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageTest.cs#L35

A good additional test here would be this same GetDefaultLanguageTest, but on a thread without culture set. 
See helper here:
https://github.com/microsoft/Power-Fx/blob/2cace9a65b3a98e792ba0072cd2a2a4c9d27d191/src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs#L876

**Comment by nguhoa** [comment]
fixed in https://github.com/microsoft/Power-Fx/pull/1202
