### ISSUE TITLE
Comparing a number and a string should be an error, not a warning

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1207]
Excel supports `If( 2 = "2", 3, 4 )` and returns 4, because it is comparing not just the value but the type and not coercing.  Power Fx has followed this same pattern and gives the same result, but because it is statically typed, it doesn't make sense.  We offer a warning today but still return the 4.  **We should change the warning to an error.**  The other option is to support coercion in this case, but that would result in a different behavior from Excel.

**Comment by LucGenetier** [comment]
Looks like Excel doesn't coerce string/numbers for comparisons
Numbers seem always lower than strings

<img width="107" alt="image" src="https://user-images.githubusercontent.com/69138830/227224321-d864951f-cbb9-4df7-98ec-40e791fafddf.png">

As a result 2 = "2" is equal to 2 = "4" and will always be false.

**Comment by LucGenetier** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/69138830/227225599-88a0044a-6029-4540-aa3c-f21ae017439c.png">

**Comment by MikeStall** [comment]
Gate it:
Only be an error if new PowerFxV1Compatibility flag is set (see #1281). So this is not a breaking change.
