### ISSUE TITLE
DateTimeFormat.UTC is not supported

### ISSUE THREAD

**Issue by xieofxie** [microsoft/Power-Fx#1240]
For example, this will not work `Text(Now(), DateTimeFormat.UTC )`. We will get `utc` as the result.
It is not supported as document said https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-text#predefined-datetime-formats

In the test it is said:
```
//Excel doesn't support DateTimeValue function or the DateTimeFormat formats
>> Text(DateTimeValue("March 30, 2022 5:30 PM"), DateTimeFormat.UTC)
"2022-03-31T00:30:00.000Z"
```
Does it mean it is not supported or it is a bug?

**Comment by MikeStall** [comment]
Blocked on #1241 

UTC is not supported in C# side, but could be implemented. 
Notes from Carlos:

 The logic from PAClient is fairly simple:

```
// Display the date in utc using ISO 8601 format for datetime representation (http://www.w3.org/TR/NOTE-datetime).
// We have chosen the profile to display the time in the following format:
// Times are expressed in UTC (Coordinated Universal Time), with a special UTC designator ("Z") i.e.YYYY-MM-DDThh:mm:ss.sZ.
const formatInUtc = format.replace(/utc/gi, dt.toISOString());

// Return the datetime value in UTC format.
if (formatInUtc !== format) {
   return formatInUtc;
}
 


```

**Comment by MikeStall** [comment]
Note example from top is from NotYetReady tests: https://github.com/microsoft/Power-Fx/blob/f729504abb13120fc44642b9c81455b33989fd97/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/NotYetReady/Text.txt#L57

This is showing value from PowerApps, but in NotYetReady since not yet supported in C#.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1246
