### ISSUE TITLE
Intellisense should differentiate between not recognized and not yet supported functions

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#1263]
Currently, when attempting to write Power Fx expressions which work in Power Apps but not yet using the OS library intellisense says the function is not recognized. Example:

![image](https://user-images.githubusercontent.com/72627659/228087110-c6fb653b-0a5e-4646-8bc0-50ccf351251e.png)

Our customers are often confused by this message and reach out via support channels since the Power Fx they know from Power Apps doesn't work as expected.

Instead, we should have different messaging around the language gaps and truly unrecognized functions by saying something along the lines as "Recognized but not yet supported function" for functions that work in Power Apps but not in cards.

**Comment by anderson-joyle** [comment]
We should also check if the host has a customized list of supported functions. Maybe a different error message in case the function is explicitly disabled by the host?
A mutable function list is possible since https://github.com/microsoft/Power-Fx/pull/764.
