### ISSUE TITLE
Reconcile output format for Float and Decimal

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1265]
Today (with the Decimal Infra PR), `Float( 1e20 )` results in `1E20` and `Decimal( 1E+20 )` results in `120000000000000000000`.  We need to rationalize if these should the same, different, and what formats we should use by default.

**Comment by MikeStall** [comment]
We should have a test that explicitly calls Text function: 
Text(Float(1e20))  // "1e+20"
Text(Decimal(1e20)) // "100000000000000000000"

**Comment by gregli-msft** [comment]
Addressed by https://github.com/microsoft/Power-Fx/pull/1709
