### ISSUE TITLE
DatabaseSimulation_TestTimeout is unstable

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/Power-Fx#1266]
When run alone, it works.
When run with a bunch of other tests in parallel, it's likely going to fail.

 DatabaseSimulation_TestTimeout(expr: "Patch(Table, First(Filter(Table, MyStr = \"Str3\")"...)
   Source: DatabaseSimulationTests.cs line 59
   Duration: 575 ms

  Message: 
Assert.Throws() Failure
Expected: typeof(System.Threading.Tasks.TaskCanceledException)
Actual:   typeof(System.OperationCanceledException): The operation was canceled.
---- System.OperationCanceledException : The operation was canceled.

  Stack Trace: 
CancellationToken.ThrowOperationCanceledException()
CancellationToken.ThrowIfCancellationRequested()
EvalVisitor.CheckCancel() line 84
Library.LazyFilterAsync(EvalVisitor runner, EvalVisitorContext context, IEnumerable`1 sources, LambdaFormulaValue filter, Int32 topN) line 664
Library.FilterTable(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args) line 388
<<StandardErrorHandlingAsync>b__0>d.MoveNext() line 103
--- End of stack trace from previous location where exception was thrown ---
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 276
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 245
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 245
ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig) line 166
CheckResultExtensions.EvalAsync(IExpressionEvaluator expr, CancellationToken cancellationToken, ReadOnlySymbolValues symbolValues) line 56
<<DatabaseSimulation_TestTimeout>b__0>d.MoveNext() line 81
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
CancellationToken.ThrowOperationCanceledException()
CancellationToken.ThrowIfCancellationRequested()
EvalVisitor.CheckCancel() line 84
Library.LazyFilterAsync(EvalVisitor runner, EvalVisitorContext context, IEnumerable`1 sources, LambdaFormulaValue filter, Int32 topN) line 664
Library.FilterTable(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args) line 388
<<StandardErrorHandlingAsync>b__0>d.MoveNext() line 103
--- End of stack trace from previous location where exception was thrown ---
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 276
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 245
EvalVisitor.Visit(CallNode node, EvalVisitorContext context) line 245
ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig) line 166
CheckResultExtensions.EvalAsync(IExpressionEvaluator expr, CancellationToken cancellationToken, ReadOnlySymbolValues symbolValues) line 56
<<DatabaseSimulation_TestTimeout>b__0>d.MoveNext() line 81
--- End of stack trace from previous location where exception was thrown ---

**Comment by MikeStall** [comment]
Probably just TaskCanceledException vs. OperationCanceledException  ?
https://stackoverflow.com/questions/34359129/operationcanceledexception-vs-taskcanceledexception-when-task-is-canceled

I think we just need a test update.
