### ISSUE TITLE
More coercion helpers 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1268]
Add these methods to TypeCoercionProvider
https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs

        // Switch on existing TryCoerceTo methods 
        static bool TryCoerceTo(thist FormulaValue value, FormulaType targetType, out FormulaValue result);

        // Determines statically if TryCoerceTo will succeed. 
        static bool CanPotentiallyCoerceTo(this FormulaType source, FormulaType target);

This is generalizing from #1045,  #1127. 

Also make this work with aggregate types, Record/Table. This means calling recursively on each field.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1270
