### ISSUE TITLE
intellisense function signatures get hidden by User suggestion

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1278]
User property shows up function parameter intellisens.  And this covers the signature

Not good: (repro with fx test site)
![image](https://user-images.githubusercontent.com/1538900/228624858-1ed893bc-5042-4aa8-b911-74276cb39852.png)

Should look more like:
![image](https://user-images.githubusercontent.com/1538900/228625055-e8bef537-8eb4-4660-b6b9-c8b302fcc3d4.png)

**Comment by MikeStall** [comment]
This is a bug with Monaco.  Not specific to User function or LSP 
UFB team is tracking request.

**Comment by jas-valgotar** [comment]
Should we consider somehow not showing the `User` object in Intellisense? I feel `signature info` > `User` object

**Comment by MikeStall** [comment]
Per suggestion above - 
normally, completion list isn't showing until after the 1st character is typed.  That avoids the conflict with signature info. 
Whereas 'User' in a parameter list is showing immediately  (before a character is typed), and hence overlap. 

We could avoid showing completion lists until after the 1st char is typed, and hence avoid this situation.
