### ISSUE TITLE
Null object reference for negate of date/datetime/time

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1294]
The interpreter's Negate function can't handle a non-numeric input.  And it shouldn't have to, as the compiler should block these operations from appearing in the IR.  
```
> Time(1,0,0)
Time(1,0,0,0)

> -Time(1,0,0)
One or more errors occurred. (Object reference not set to an instance of an object.)

> IR(-Time(1,0,0))
Negate:T(Time:T(Coalesce:n(Float:n(1:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)))

> IR(-Date(2,0,0))
Negate:D(Date:D(Coalesce:n(Float:n(2:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)))

> IR(-DateTime(2,0,0,0,0,0))
Negate:d(DateTime:d(Coalesce:n(Float:n(2:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)))
```
They are permitted partially because `a-b` translates into `a+-b` and that is needed for `DateTime(1,0,0,0,0,0)-Time(1,0,0)`.  Before they get to Negate, the opcode is replaced with a binary op for doing subtraction.
```
> IR(Now()-Time(1,0,0))
SubtractDateAndTime:d(Now:d(), Time:T(Coalesce:n(Float:n(1:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)))

> IR(Time(2,0,0)-Time(1,0,0))
TimeDifferenceDecimal:w(Time:T(Coalesce:n(Float:n(2:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)), Time:T(Coalesce:n(Float:n(1:w), 0:n), Coalesce:n(Float:n(0:w), 0:n), Coalesce:n(Float:n(0:w), 0:n)))
```

**Comment by MikeStall** [comment]
Callstack is:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerFx.Functions.Library.NumericNegate(IRContext irContext, NumberValue[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass410_0`1.<StandardErrorHandling>b__0(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, T[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass409_0`1.<<StandardErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PowerFx.EvalVisitor.Visit(UnaryOpNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig)
