### ISSUE TITLE
Decimal: FormulaValue.ToExpression should show float vs. decimal 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1314]
NumberValue should serialize as `Float(123)`, whereas DecimalValue should serialize as `Decimal(123)`

Compact mode can still show them both as just `123`, which will mitigate .txt updates

**Comment by MikeStall** [comment]
Starting draft at #1315.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1366
