### ISSUE TITLE
Min/Max should not scan arguments for date/time

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1329]
Instead it should follow the first type rule.

**Comment by MikeStall** [comment]
Min /Max can operate on different types (numbers, decimal, DateTime) 
Today, they scan all types in the arg list to determine which type. Instead, it should decide 
 
Gate off the V1 flag since this would be language breaking.

**Comment by MikeStall** [comment]
Removing BreakingInternals flag since this should be gated on v1 feature flag instead.
