### ISSUE TITLE
Support only Decimal and Number types when specifying the return type for the field requiring Number

### ISSUE THREAD

**Issue by justinpark0916** [microsoft/Power-Fx#1356]
Cards has a property that requires Number/Decimal. Currently, it seems like allowing multiple types is only allowed in `FormulaType.String` case. 

We would need a feature for `FormulaType.Number` so that this supports both `FormulaType.Number` and `FormulaType.Decimal`

**Comment by MikeStall** [comment]
Related to #1357, #1125. May need to get more details here.

**Comment by MikeStall** [comment]
This applies to  CheckResult.SetExpectedReturnValue().

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1453

**Comment by nguhoa** [comment]
CARDS would want coercion to allow both decimal and number. 
in a number field, maybe Float(1.22) and Decimal(1.22) should allowed Also 1 and 1.2 should be allowed

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1500
