### ISSUE TITLE
Support Enum for specifying return type

### ISSUE THREAD

**Issue by justinpark0916** [microsoft/Power-Fx#1357]
Found out currently we don't have a way to set the return type for `Enum` type. We would like to display a message when a wrong type is inserted to the `enum` property.

For example from PowerApps:
![image](https://user-images.githubusercontent.com/104940715/231598187-977e0f33-5c74-4de7-92c1-884464725633.png)

**Comment by MikeStall** [comment]
Related to #1125.  May need to get more details here.

**Comment by justinpark0916** [comment]
Closing the issue since I cannot reproduce the behavior in PowerApps :)
