### ISSUE TITLE
Sequence function could overflow in stepping forward

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1368]
Both for float and decimal, there is no protection on x += step in LazySequenceFloat and LazySequenceDecimal.  Likely both functions should return an ErrorValue when this occurs and include that in the resulting table.  The code will need to be restructured a bit to accommodate this.

**Comment by nguhoa** [comment]
Fixed as in https://github.com/microsoft/Power-Fx/pull/1459
