### ISSUE TITLE
Some interpreter tests don't work with non-V1CompatibilityRules, but work on Canvas

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1396]
We have a set of tests that don't work when run through the interpreter without V1CompatibilityRules, a part of PowerFxV1.  One would think that is a problem, but alas, Canvas doesn't use the interpreter and the tests pass on Canvas.  Rather than fixing the bug in the short term, we need to skip these tests here and run them on Canvas in another way.

For example, `DateTime(1900,1,1,12,0,0) <= Time(12,0,0)` and `Time(1,0,0) <= DateTime(1899,12,30,1,0,0)` with all comparison operators including =.

**Comment by CarlosFigueiraMSFT** [comment]
Fixed by #1694
