### ISSUE TITLE
New PowerFx formula bar does not highlight open/close parentheses or curly brackets when on same line and ctrl + F does not open find window

### ISSUE THREAD

**Issue by kayetter** [microsoft/Power-Fx#1424]
I keep trying to use the new Power Fx experimental feature for the formula bar but I keep turning it off. 
Often I write code on one line with complicated if statements or AddColumns statements.  Keep in mind that you cannot format the code if there are any errors. Often errors occur because you are missing a closing ")" or "}". In the current formula bar editor, the editor will highlight the matching bracket or parentheses to the best of its ability which is important for troubleshooting to remove errors so you can format the code and clean it up. 

In the new formula bar the only indication of an open or close statement is the very faint line connecting the lines together. This is only accessible with properly formatted, error-free code. This just isn't enough if you have errors and can't format the code. Can you provide an extension that will highlight matching brackets and parentheses? I really can't use the new feature.

Also, pressing ctrl F in the current formula bar would open a small find window in the top right (very useful). The new formula bar does not have ctrl F find, rather it goes to the search menu item on the far left vertical menu panel (not so useful).

See screenshots below:
# No closing brackets highlighted (new formula bar):
![image](https://user-images.githubusercontent.com/22959546/233868664-2652953e-d4a3-4d85-af0c-6ebcdf48a2ea.png)

# closing brackets highlighted (current formula bar):
![image](https://user-images.githubusercontent.com/22959546/233868714-7c0989c5-aaba-4099-91fb-d9302f1b94e3.png)

**Comment by akshar2401** [comment]
Hi @kayetter, thank you for reporting this issue and your feedback on find + replace feature. As we announced earlier this year, we are actively considering new functionalities for the new formula bar and that includes find and replace as well. We've fixed the bracket highlighting issue that you encountered, and it is rolling out as i write this reply. It should be fully available in production by the end of this month. Thank you once again for bringing this to our attention. We would love to hear any other feedback you may have and would encourage you to fill any other issue related to new formula bar in forum here https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1.
