### ISSUE TITLE
Error when provided empty expression to the field with "Specify Return Type" feature

### ISSUE THREAD

**Issue by justinpark0916** [microsoft/Power-Fx#1425]
We found out that we are seeing this error("The type of this expression does not match the expected type `Type`. Found type `ObjNull`.) when an empty expression is provided to the field with `Specify Return Type` feature. Instead of this, we would like to avoid providing an error message when an empty expression is passed.

![image](https://user-images.githubusercontent.com/104940715/234017980-d690e292-39e7-4848-9ff0-48d2900f9e74.png)

Attached the unit test to reproduce:
```
        [Fact]
        public async Task test()
        {
            // Setup
            var scope = new EditorContextScope((expr) => new CheckResult(new Engine())
                    .SetText(expr)
                    .SetBindingInfo()
                    .SetExpectedReturnValue(FormulaType.String));

            // Act
            var result = scope.Check("");

            // Assert
            Assert.True(result.IsSuccess);
        }
```

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1475
