### ISSUE TITLE
A bug in TexlLexer computes overlapping spans for two single line comments on two consecutive lines

### ISSUE THREAD

**Issue by akshar2401** [microsoft/Power-Fx#1444]
There's a bug in TexlLexer that computes overlapping spans for two single line comments on two consecutive lines. 
For example, 
the following expression is valid and has two singe comments on first and second lines respectively.
`//Comment one \n//Comment Two \n "String One\n";"String One \n String Two \n";`

Texl Lexer computes the end of the first comment token (// Comment One) to be one more than the start of the second comment token. The end of tokens is exclusive while start is inclusive. The span for "//Comment One \n" is computed as [0, 16) and the span for "//Comment Two \n ' is computed as [15, 31).  According to these spans, first comment ends on index 15 as the end 16 is exclusive and second comment starts on index 15 as start is inclusive. The correct spans should be [0, 16) and [16, 31) respectively.  

Since the spans are overlapping and monaco-editor doesn't support overlapping tokens and it would drop the second comment since it overlaps with the first one, we would not be able to color the second comment like shown below:
<img width="155" alt="image" src="https://user-images.githubusercontent.com/25670945/234623064-0ba02669-e9d9-4543-9552-b2a803ef8283.png">

I added a test to test this but it fails so i skipped it for now.  The test is in the file https://github.com/microsoft/Power-Fx/pull/1420/files#diff-96d979019aa164df966d238d47ec982a988f95c486c6ebee07293baf12b832e9 introduced in pr that extends language server to support semantic tokenization
The test should be enabled after this bug has been fixed. 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/25670945/234626034-d1b95e87-30e4-4680-89d3-43ad2167fff0.png">

The bug happens in the TexlLexer.cs file in the while loop in LexComment() function https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs#:~:text=//%20Preceding%2C,%3E%200)

<img width="307" alt="image" src="https://user-images.githubusercontent.com/25670945/234624046-5df6812a-8c4f-474e-9943-9571d5afcb81.png">

This while loop is consuming all the new lines before the start of single line comment and setting the starting position of the single line comment before any preceding new lines. In the example above, it consumes "\n" at the of //Comment One \n as a part of second comment and adjusts the starting position of second comment from 16 to 15 since it preceded by \n of //Comment One \n. It should not consume any preceding \n if those \n were consumed by the first comment

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1498
