### ISSUE TITLE
Text( Blank() ) should return Blank()

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1458]
For the 1 argument version of Text, which is serving as a Power Fx type converter, we should preserve Blank() flowing through.  That means that Text( Blank() ), Text( If(1<0, 2) ), and Text( ParseJSON( "null" ) ) should all return Blank().

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1478
