### ISSUE TITLE
stronger enforcement for records  in custom functions 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1490]
Today, with V1 semantics, any record coerces to any other record.  This is too loose for custom functions that take records. 

Goals:
1. No change to Patch/Collect
2. Ideally, a custom function can wrap Patch/Collect
3. We want to catch cases where a function expects Accounts, but gets passed a Contact.

So update to be this: Modify Custom function handler so that for a parameter that expects a record, passing in extra fields is an error.  Passing in missing fields is ok.

**Comment by jas-valgotar** [comment]
This function maybe useful in matching fields. (https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Interpreter/Functions/Extensions.cs#L52)

**Comment by MikeStall** [comment]
Suppose we have a function that takes:
`{ X : Number, Y:Number }`

There are several cases to try:

Example | Kind |  Change
--- | --- | --- 
`{ X : Number, Y: Number }`  | perfect | 
`{ X : Number, Y: Number, A : Number }`  | extra, A?  ... ignored | !!! Should be an error case (this bug) 
`{ X : Number }`  | missing Y  ... fill in blank  | 
`{ A : Number}`  | No relation!!!!  |  Today, this is allow if Extra+ missing are allowed.  But that's too flexible.   By making extra fields an error, that will make this an error. 
`{ X : String }`  | Coercable !!  | 
`{ X : { Nested: String }}`  | Error - not coercable  |

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1555
