### ISSUE TITLE
If function should follow first type rule

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1497]
```
> If( false, {a:1}, {b:2} )
{}

> If( true, {a:1}, {b:2} )
{}
```

The first argument should determine the type, a change from the current intersection semantics in Canvas.  The `true` case should return {a:1}.  The `false` case should return an empty record, as it is today.

**Comment by CarlosFigueiraMSFT** [comment]
Resolved by #1507
