### ISSUE TITLE
When source and target are of same type, should return true for CanPotentiallyCoerceToTargetType

### ISSUE THREAD

**Issue by xieofxie** [microsoft/Power-Fx#1570]
https://github.com/microsoft/Power-Fx/blob/ace1d1fa33c34eb40a96404de59b67562779250f/src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs#L345

Since they are not aggregated type, we should return true to support more types like Decimal, Guid etc.

https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Public/Types/FormulaType.cs

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1572
