### ISSUE TITLE
Does TryCoerceToRecord loop the wrong fields?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/Power-Fx#1571]
https://github.com/microsoft/Power-Fx/blob/ace1d1fa33c34eb40a96404de59b67562779250f/src/libraries/Microsoft.PowerFx.Interpreter/Marshal/TypeCoercionProvider.cs#L238

In my understanding, when we coerce source to target, we should check that every target's field exists in source but not the way around. In current implementation, for the passing scenario like below, the newResult (`{![key:n]}`) doesn't have type recordType (`{![key:n, value:s]}`).

```
var record = FormulaValue.NewRecordFromFields(new NamedValue("key", FormulaValue.New(1)));
var recordType = RecordType.Empty().Add(new NamedFormulaType("key", FormulaType.Number)).Add(new NamedFormulaType("value", FormulaType.String));
record.TryCoerceTo(recordType, out var newResult);
```

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1572
