### ISSUE TITLE
Intellisense suggest shouldn't catch all. 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1573]
Suggest has a catch all: 
https://github.com/microsoft/Power-Fx/blob/ace1d1fa33c34eb40a96404de59b67562779250f/src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/Intellisense.cs#L65

Intellisense should never throw - even on invalid input.  Any exception is a bug. 
This can be hiding real issues.  Instead, let the exception bubbleup and a top-level can _catch and log it_.  LSP already does this today with #251. 
Ack that if we did have an exception, we'd like to ignore it and not destroy the process. 

Verify we're not breaking power apps - we may need to add a top level catch there, or something. 

This should let us remove Exception field on result.

**Comment by LucGenetier** [comment]
Fixed with https://github.com/microsoft/Power-Fx/pull/1576
