### ISSUE TITLE
regression of DateTimeValue, DateValue function

### ISSUE THREAD

**Issue by xieofxie** [microsoft/Power-Fx#1608]
We should get 1,1,1 for the following format instead 1899, 12, 30

![image](https://github.com/microsoft/Power-Fx/assets/2876650/69eeaf18-9635-47de-b034-794851011d5b)

**Comment by xieofxie** [comment]
0002 did work.. it looks like 0001 causes some bug

![image](https://github.com/microsoft/Power-Fx/assets/2876650/a2711cf5-93c2-4749-942f-a43d37b1d95b)

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1629
