### ISSUE TITLE
Set() doesn't coerce Decimal to Number and vice versa!

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#1659]
Should `Set(x, 1); Set(x, Float(1))` work?
Today it doesn't. Since Set(x, 1) will type `x` as `decimal`.

**Comment by MikeStall** [comment]
If X is a defined as a Decimal, then Set(x, Float(1)) ought to work. 
Ideally, PA and Fx would handle same way.

**Comment by MikeStall** [comment]
This is the counterpart to the same issue for Patch/Collect: #1383
