### ISSUE TITLE
config.EnableRegExFunctions() doesn't indicate that these functions are Preview

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1663]
IsMatch, Match, and MatchAll functions are not finished, we need to reconcile the regular expression language here with what is in Canvas.  

We need some way to indicate to a host that these functions are not GA.  Currently, all a host needs to do is call `config.EnableRegExFunctions()` which looks like `config.EnableSetFunction();` and `config.EnableParseJSONFunction();` which are GA.

Either a Engine.Features flag needs to be used, or the name of the enable function needs to be descriptive, something like `config.EnableRegExFunctions_Experimental();`

**Comment by MikeStall** [comment]
We currently require the pattern is a string literal - that's good. 
But we:
- allow more things in C# than we allow in PA
- handle some cases differently between C# and PA 

So we will need to change semantics of the pattern to ensure C#/PA behave the same.
