### ISSUE TITLE
Custom SetProperty function with number value

### ISSUE THREAD

**Issue by NavneetThekkumpat** [microsoft/Power-Fx#1669]
Running Testengine with this SetProperty
``` 
SetProperty(Rating1.Value, 5);
```
PowerFx.Engine.**Check** and **Eval** functions fail with the below error
<img width="900" height="280" alt="image" src="https://github.com/microsoft/Power-Fx/assets/98551644/42540f95-e2aa-45c8-8b33-f0ea4f9bfb58">

**Workaround right now is setting NumberIsFloat ParserOptions to true**  and it runs successful.

**Comment by jas-valgotar** [comment]
This is related to https://github.com/microsoft/Power-Fx/issues/1659
This should be a fix here: https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Interpreter/CustomFunction/CustomSetPropertyFunction.cs#L72
