### ISSUE TITLE
[CJO] Blank() in [1, Blank(), 2] returns "Unknown Error"

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/Power-Fx#1681]
Blank() in [1, Blank(), 2]
{InRecordTable:b(Blank:N(), Table:*[Value:w]({Value: 1:w}, {Value: Blank:N()}, {Value: 2:w}))}
--> Error: Validation - Unknown error

1 in [1, Blank(), 2]
{InScalarTable:b(1:w, Table:*[Value:w]({Value: 1:w}, {Value: Blank:N()}, {Value: 2:w}))}
--> true

**Comment by MikeStall** [comment]
Fixed in latest build. Which PR?
