### ISSUE TITLE
Remove in ForAll return type issue?

### ISSUE THREAD

**Issue by jorisdg** [microsoft/Power-Fx#1685]
Set(list, Table({ Name: "One", ID: 1}, { Name: "Two", ID: 2}))
Set(list2, Table(First(list)))

ForAll(list2, Remove(list, ThisRecord))

the return value of this expression:
![image](https://github.com/microsoft/Power-Fx/assets/16008040/f4324f4d-2236-4ef6-85bf-d5408a054d43)

if you get that value and try to iterate the fields on the row like this:
![image](https://github.com/microsoft/Power-Fx/assets/16008040/e7e55b95-b0b6-4cbd-9b4d-fa01f1da0ab1)

you get an exception:
{"InMemoryRecordValue.TryGetField(Value): Wrong field type. Returned b, expected *[ID:w, Name:s]."}

at Microsoft.PowerFx.Types.RecordValue.<GetFields>d__3.MoveNext()\r\n   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)\r\n   at (my code)

**Comment by anderson-joyle** [comment]
Other functions are producing a similar error result:
`ForAll(t, Coalesce(Blank()))`
