### ISSUE TITLE
Text function: Block use of format string when input is non-numeric at compile time

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1703]
Today we allow `Text` to be called with a string, Boolean, GUID, etc. along with a format string.  The format string appears to be ignored.   Canvas does the same.
```
> Text( "123.456", "$ ##.####" )
"123.456"

> Text( true, "$ ##.####" )
"true"

> Text( GUID(), "$ ##.####" )
"b9866596-378c-4d19-b79b-b967f39996a7"
```
This is dangerous because Excel supports coercion from string to number in this scenario.  Which is fraught with peril as this is a runtime check:
![image](https://github.com/microsoft/Power-Fx/assets/15149773/b72e8403-2930-49f9-beae-1d390b0ab671)

Where we are different from Excel is that we are strongly typed.  We can use that to provide a better, less error prone experience.

The desired experience:
1. For all types, `Text` without a format string works as it does today.
2. For number, date, date/time, and time - no change.  Format string works as it always has.
3. For all other types, where a format is provided, we will generate a compile time error.  This avoids us needing to support the string coercion to number that Excel supports today, something that we can add in the future if the need arises as we would be removing a portion of this block.

There are tests for this change in https://github.com/microsoft/Power-Fx/blob/gregli/text-excel/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_ExcelCompat.txt.

**Comment by nguhoa** [comment]
Fixed in 1711
