### ISSUE TITLE
Text function: Add consistent escaping to format string

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1704]
Escaping in the Text format string is essential.  As Excel and Power Fx pluck more characters for placeholders, it is critical that makers have a way to reliably insert the character that they want.

Excel handles escaping of placeholder characters in two ways:
- Backslash before each character
- Double quoted string within the format string
It does not support single ticks for escaping, the ticks are passed through.

![image](https://github.com/microsoft/Power-Fx/assets/15149773/6410b275-239a-41b7-942d-57091036c4ad)

Now the C# interpreter:
```
1> Text( 123.456, "mmm ddd yyy" )
"May Wed 1900"

2> Text( 123.456, """mmm"" ddd yyy" )
"mmm Wed 1900"

3> Text( 123.456, "\m\m\m ddd yyy" )
"\5\5\5 Wed 1900"

4> Text( 123.456, "'mmm' ddd yyy" )
"'May' Wed 1900"

5> Text( 123.456, "#.##" )
"123.46"

6> Text( 123.456, "#.""##""" )
"123##"

7> Text( 123.456, "#.\#\#" )
"123##"

8> Text( 123.456, "#.'##'" )
"123##"

9> Text( 123.456, "#.##'" )
"123.46"
```
Lines 3, 8, and 9 are incorrect, and lines 6-8 are missing the decimal point.  Canvas gets many of these wrong in other interesting ways.

Tests for these scenarios can be found in [Power-Fx/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_ExcelCompat.txt at gregli/text-excel · microsoft/Power-Fx (github.com)](https://github.com/microsoft/Power-Fx/blob/gregli/text-excel/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_ExcelCompat.txt)

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1716
