### ISSUE TITLE
Text function: Block unsupported placeholders

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1705]
Excel supports many more format placeholders than we do.  Some of these would clearly add value to Power Fx, such as `?` and `/` but we aren't in a position to do all this work now.  Others we may want to add down the road, and we'd like to keep our options open.

Until we are ready to implement all of these, we should block the following placeholders:
1. `?` - Whitespace padded digit (similar to `0` which zoer pads).
2. `#/`, `0/`, and `?/` - Fraction notation.  We can't outright block all `/` because it is common in `mm/dd/yy`, but we can block it if it is used in a numeric context.
3. `[`...`]` - Used in Excel for many scenarios, including conditional sections and elapsed time.  We are going to block them all for now and bring them back when needed.  This means we will be blocking [$-en-US], the subject of [#1706 ](https://github.com/microsoft/Power-Fx/issues/1706).
6. A third `;` - More than three sections.  Excel supports up to four, with the last being what to display if the input is text.  As we are strongly typed this may not make any sense long term.
4. `_` - Whitespace padding.  Sucks up the following character, we need to decide what to do long term, if anything.
5. `*` - Alignment.  Again, sucks up characters around it, we need to decide what to do long term, if anything.
6. `:` when used next to number placeholders - Time notation.  As with `/`, we can't outright block it because it is popular for `hh:mm:ss`.  We'll allow only if adjacent to a time value placeholder (allowing for whitespace).  Excel's rules on this aren't very clear.
7. `@` and `General` (case insensitive) - General text placeholder.  These things are just weird, I haven't deduced how exactly they work.  They seem to do similar things, but act on numbers and strings in opposite ways.  For now, block.

We also need to check the placeholders that C# supports that we do not, and pass these through as regular characters.  At present, we are interpreting permille and single ticks when we should not be.  For example in src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/TextOverride.txt there is `Text(100, "#%‰'eE:")` which is waiting on this issue to be resolved.

Tests are available here: https://github.com/microsoft/Power-Fx/blob/gregli/text-excel/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Text_ExcelCompat.txt

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1716
