### ISSUE TITLE
Text function: Block [$-en-US]

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1706]
There are two problems with this notation.

First, we have the usage of this syntax backwards from Excel.  Excel uses this to specify the *output* locale, which we use the third argument to Text for.  We use it to mean the *input* locale.  I believe long term we probably want a different syntax for this that does not conflict with Excel, such as `[@-en-US]`.

Second, this notation changes more than just thousands and decimal separators, it also impacts the placeholder letters used for day, month, and year.  I might say that we could get away with just using en-US placeholders, but the specification for something like `[@-fr-FR` is right there, it seems like an obvious bug to ignore it.

Consider this spreadsheet in English:
![image](https://github.com/microsoft/Power-Fx/assets/15149773/913d9a69-5130-4ead-a28d-e985dc56e457)

Here is how it looks in French:
![image](https://github.com/microsoft/Power-Fx/assets/15149773/b04d8ce4-dc8c-440f-92ac-89f816551bf5)

Literally the same workbook, changing behavior depending on the viewer's locale.  This is exactly what the `[@-en-US]` specifier is designed to address.  

But for now, we should just block `[$-en-US]` and not introduce `[@-en-US]`.  We'll have to resolve this when we get to Power Fx 1.0 in Canvas.  We can live with just en-US for the time being for these format strings.  The maker can still specify the output locale with the third argument to Text, they just need to specify the format string itself in English (mm, dd, yy, command, and dot) until we get this done.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1716
