### ISSUE TITLE
How can I generate a list of functions implemented by the Power-Fx library and a missing function list?

### ISSUE THREAD

**Issue by ApolonTorq** [microsoft/Power-Fx#1730]
Issue #284 references the list of power apps functions at https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/formula-reference and requests that the missing functions be implemented.

If an application takes a dependency on the Power-Fx library, then the application users often have an expectation of being able to read up on the supported functions. The Power Apps formula page is a good reference except that the application user wouldn't know which functions are supported and which are not in the non-Microsoft application they are using. Yes it may be apparent in the auto-completion expression editor UI, but being able to run through what functions are available ahead of time would be very useful.

Given this context, how can I generate a list of functions implemented in the Power-fx library?
e.g. to create a page similar to the [Microsoft formula reference page](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/formula-reference) but with only supported functions listed. Alternatively, it could be a github documentation page within the project itself.

**Comment by anderson-joyle** [comment]
There are mainly two places you can take a look:

- [Builtin core functions](https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Texl/BuiltinFunctionsCore.cs): Contains a list of all implemented non-mutation functions.
- [Mutation functions](https://github.com/microsoft/Power-Fx/tree/main/src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation): List of functions that changes the data source. Please keep in mind that not all overloads are currently available e.g. Patch function support only `Patch(table, record, ...)`.

**Comment by ApolonTorq** [comment]
Thanks!
