### ISSUE TITLE
Text function: DateTimeFormat enum can be used in a non-strongly typed manner

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#1768]
Before we had strongly typed enums, enums and strings/numbers were interchangeable.  Which meant that the Format parameter to the Text function needed a way to support `DateTimeFormat.LongDate` as a string.  The solution was to have a special string, `'longdate'` in this case, that the Text function would key off of.  This is hacky and contradicts the normal handling of single ticks and other letters in the format string.  

For example, and see how the addition of another character changes the meaning completely:
```
1> Text( Now(), DateTimeFormat.LongDate )
"Wednesday, August 16, 2023"

2> Text( Now(), "'longdate'" )
"Wednesday, August 16, 2023"

3> Text( Now(), "'longdate'z" )
"'long16ate'z"
```

Times have changed and we now have strongly typed enums.  We should use it to differentiate from custom format strings.  As the [docs describe](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-text), one should be able to use either the enum or a custom format string, but not both.  

In other words, example 2 above should look like example 3, without the extra `z`.

**Comment by gregli-msft** [comment]
Dup of https://github.com/microsoft/Power-Fx/issues/1760

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1761
