### ISSUE TITLE
Errors for numeric literals 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1777]
Today, this will give a compiler time error because the literal is too large
`1000000000000000000000000000000000000000000000000 +1 // compiler error`

The range here needs to be configurable per-backend. SQL has a much smaller range of numeric literals. 
For example, in SQL, this (1 followed by 15 zeros) should be an error:
`1000000000000000 + 1`

1. Where does this error come from?
2. What's the right way to configure per-backend?

**Comment by MikeStall** [comment]
fwiw: SQL goes to 23.10 

But, good principle here is that _a number at compile time should come out at runtime_.   
It's ok to have extra errors (and limit the range) -we can always expand it later.

**Comment by MikeStall** [comment]
See SQL check in ValidateNumericLiteral,  https://github.com/microsoft/Power-Fx-Dataverse/pull/274

**Comment by gregli-msft** [comment]
Likely these lines in TexlLexer.cs need to support a configurable limit, passed in by the host through engine settings or parser config.  https://github.com/microsoft/Power-Fx/blob/a9ea04cf0c7866b48fb48a7fb315634aecca03a4/src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs#L1247C1-L1255C66

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx-Dataverse/pull/316

**Comment by MikeStall** [comment]
To clarify - this was solved in Dataverse side.
