### ISSUE TITLE
DateDiff fails when TimeUnit enum prefix is missing

### ISSUE THREAD

**Issue by jcoc611-microsoft** [microsoft/Power-Fx#178]
`DateDiff` examples from the [official docs](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-dateadd-datediff) like this one fail:

```
DateDiff(Now(), DateValue("1/1/2014"), Months)
```

They only work if `TimeUnit.` is prefixed to the unit, so this works fine:

```
DateDiff(Now(), DateValue("1/1/2014"), TimeUnit.Months)
```

Since the official docs are in the non-prefix format, should this be fixed in the parser?

**Comment by lesaltzm** [comment]
This is by design, we've found that unqualified enum access has been a major source of bugs, and didn't bring support into non-canvas PowerFx. We should update the docs. 

@gregli-msft
