### ISSUE TITLE
Formula Bar while sorting should deal with symbols (suggestions) wrapped with single quote.

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#1784]
-Sorting of suggestion does not take into account that it can be wrapped in IdentifierDelimiter `'` (i.e. 'AAD User' table)
-Since in lexicographic sort `'` comes before any alphabet, all the suggestions starting with alphabet are buried at the end.

See below behavior in PowerApps

![image (2)](https://github.com/microsoft/Power-Fx/assets/32079188/955e1beb-a828-4d2a-a701-439770d797c1)

This is more of grief in Fx, since we add all the tables in a single org policy, which means the `Accounts` table gets buried after 100s of the table...

![image (3)](https://github.com/microsoft/Power-Fx/assets/32079188/54f5d7e3-e0fd-42d0-bd02-ad5e22005454)

NOTE: The legacy bar did take into account that there can be symbols wrapped in a single quote `'` and sorted it accordingly.

![image (4)](https://github.com/microsoft/Power-Fx/assets/32079188/04c68a30-e762-4eaf-a052-3aaa51ae5f41)

**Comment by akshar2401** [comment]
Would temporarily take care of this at the UFB level

**Comment by jas-valgotar** [comment]
Issue filed for UFB team, https://msazure.visualstudio.com/OneAgile/_workitems/edit/24935881

**Comment by akshar2401** [comment]
@jas-valgotar is this fixed now?

**Comment by jas-valgotar** [comment]
Fixed via https://github.com/microsoft/Power-Fx/pull/1854 and https://github.com/microsoft/Power-Fx/pull/1884
