### ISSUE TITLE
"Union All" tables 

### ISSUE THREAD

**Issue by babrekel** [microsoft/Power-Fx#1819]
In my scenario I have multiple tables that I would like to concatenate in a purely functional manner, without use of `Collect`. While trying, I was expecting the `Concat` or `Concatenate` function to be able to do this. Note: I am biased in that I have a background in .NET development. 

Note that the semantics I'm looking for is "Union All" without deduplication. 

```
Test1 = [{a:5,b:6}]
Test2 = [{a:5,b:6}]

// expected
Concat(Test1, Test2) // Type error
Concatenate(Test1, Test2) // Type error

// workaround:
ForAll(Sequence(CountRows(Test1)+CountRows(Test2)), If(Value<=CountRows(Test1),Index (Test2,Value), Index(Test2, Value - CountRows(Test1)))) // Table({a:5,b:6},{a:5,b:6}) 
```

**Comment by rnwood** [comment]
This is an obvious gap in available functions. The community are using Ungroup() as an ugly workaround.
