### ISSUE TITLE
Add support for both EnumStore and FormulaType for OptionSet in one build

### ISSUE THREAD

**Issue by ckkashyap** [microsoft/Power-Fx#183]
We need a build of PowerFx that supports two parameters to PowerFxConfig (EnumStore and CultureInfo) AND be able to get the FormulaType for OptionSet.

**Comment by MikeStall** [comment]
Does this solve your issue: https://github.com/microsoft/Power-Fx/pull/182

**Comment by ckkashyap** [comment]
Thanks @MikeStall  - @ToddN - can you please check?

**Comment by ToddN** [comment]
@MikeStall @ckkashyap , yes, a build from this should meet our needs. By making the enum store the second argument, you force people to either provide CultureInfo or a null.  If you'd made the enum store the first argument, they could have left off the CultureInfo if they didn't have it.
