### ISSUE TITLE
SetExpectedType on record 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1860]
[1] We should give more actionable errors.

`outDecimal is type String but should be type boolean`
Or  `record can't have outDecimalMissing`  or  `record is missing outDecimal`

There could be many mismatches, but we just need to show the first one.  Users will fix and move on to next. 

[2] Probably need number/decimal coercion.
It's strictly enforcing decimal vs. float, so you have to type.      `{ out : Decimal(1234)}` vs, `{out: Value(123)}`

This also means that flipping the NumberIsFloat flag will be a massive break without them.

**Comment by jas-valgotar** [comment]
This is fixed via https://github.com/microsoft/Power-Fx/pull/1866
