### ISSUE TITLE
Text function doesn't handle sections properly for date/time values

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1922]
The result of `Text(Date(2021,9,8), "yyyy-mm-dd;mm/dd/yyyy")` is currently `"2021-09-08;09/08/2021"` in the C# interpreter, but it should be `"2021-09-08"` (since the date is greater than 0).

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1992
