### ISSUE TITLE
Text function: block formats where exponential notation has decimals

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1945]
For an expression such as `Text(13579.34567, "0.00E+0.0")`, Excel does interpret the decimal number after 'E+' and writes out the result as 1.36E+4.0. This is technically correct, but useless, as the value is always a whole number. C# currently has a wrong result: 1.35E+48 (the '8' comes from the '7' after the 135, which is rounded up). To avoid confusion, we should block this (return an error) if such format is passed to the function.

**Comment by nguhoa** [comment]
Another different between c# and excel in exponential notation when it has escaping character. 
If I have the following example that after e+ we have escaping character:
	Text(1234567.1234567, "0.000E+00\k000")
- Excel will get all 0000 after e+ as 0006 and put escaping character in the place after they get 0006 so the result is: 1.235E+00k006
- C# only get 00 before escaping character and after e+. character after escaping character is directly get from input number and the value before e also different so the result is: "1.234E+06k567".
 
But without escaping character both excel and c# behave the same:
	Text(1234567.1234567, "0.000E+00")
return 1.235E+06
 
So we will block this escaping character after exponential notation as well.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/2007
