### ISSUE TITLE
Text function: support '#' in the format for the exponential part

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1946]
For an expression such as `Text(12345.34567,"0.00E+#")`, Excel does the right thing and returns "1.23E+4". C# is incorrect, returning "12345.34E+6" - which is incorrect (the '6' comes from the '5' after .34, which is rounded up).

**Comment by nguhoa** [comment]
In the case of any non-numeric character between exponential notation and numeric character, C# is in correct with excel, it takes input number into the exponential result. So we will block this case as well.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/2024
