### ISSUE TITLE
Text function: escaped characters in the exponential notation format 'breaks' the notation

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#1948]
In an expression such as `Text(12345.34567,"0.00E+\@0")`, the C# interpreter returns an incorrect result: 12345.34E+@6 - the escaped character "broke" the exponential notation. We should either fix it to work like Excel (which returns 1.23E@+4), or block this (return an error)

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/2007
