### ISSUE TITLE
Mid() function can hang interpreter

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#195]
The interpret hangs on this expression:
  `Mid(Text(1/0, "#.000"), 1)`

Looks like hangs is in here:

        private static IEnumerable<FormulaValue> MidFunctionExpandArgs(IRContext irContext, IEnumerable<FormulaValue> args)
        {
            var res = new List<FormulaValue>(args);
            while (res.Count < 3)
            {
                // The third argument to Mid can only ever be used if the first argument is a string
                if (args.First() is StringValue stringValue) <-- arg is ErrorValue, so we loop forever.
                {
                    var count = new NumberValue(IRContext.NotInSource(FormulaType.Number), stringValue.Value.Length);
                    res.Add(count);
                }
            }

            return res.ToArray();
        }

**Comment by bryancroteau-MSFT** [comment]
https://github.com/microsoft/Power-Fx/pull/201
