### ISSUE TITLE
Connectors: Unsupported OpenApiDateTime

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1982]
Getting Unsupported OpenApiDateTime from this stack: 

"{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32603,\"message\":\"Exception Microsoft.PowerFx.Connectors.PowerFxConnectorException: Message=\\u0027Unsupported OpenApiDateTime 1/1/2018 12:00:00 AM \\u002B00:00\\u0027, HResult=0x80131500, StackTrace=\\u0027   at Microsoft.PowerFx.Connectors.OpenApiExtensions.TryGetOpenApiValue(IOpenApiAny openApiAny, FormulaValue\\u0026 formulaValue, Boolean numberIsFloat)\\r\\n   at Microsoft.PowerFx.Connectors.ArgumentMapper.GetOpenApiObject(OpenApiObject opPrms, Boolean numberIsFloat)\\r\\n   at Microsoft.PowerFx.Connectors.ArgumentMapper.GetDynamicValue(IOpenApiExtensible param, Boolean numberIsFloat)\\r\\n   at

From here:
https://github.com/microsoft/Power-Fx/blob/f3f26fb039882b75df2503198cb9824ca33ad1e0/src/libraries/Microsoft.PowerFx.Connectors/OpenApiExtensions.cs#L208

**Comment by MikeStall** [comment]
Also, This exception should have been caught and resulted in a log to the LSP's unhandled exception handler.

**Comment by LucGenetier** [comment]
https://github.com/microsoft/OpenAPI.NET/issues/533
