### ISSUE TITLE
REPL: Redefining value of same variable unexpectedly exits REPL

### ISSUE THREAD

**Issue by snizar007** [microsoft/Power-Fx#1994]
When I redefined the value type to a same variable in REPL, it showed error and exited unexpectedly.

Example 1:
<img width="611" alt="image" src="https://github.com/microsoft/Power-Fx/assets/116691001/914e14d5-c5d1-408b-934d-a2d69bf4a087">

Example 2:
<img width="596" alt="image" src="https://github.com/microsoft/Power-Fx/assets/116691001/5a3f05a8-22cd-4969-9034-29a82d24f236">

**Correct behavior:**  It should only display the error but NOT exit.

**Comment by jorisdg** [comment]
The syntax "ident = expr" is to define named formula, not set variables. Named formulas are immutable once defined.

You should use Set(ident, expr); to evalute the expr to a value, and that value will be assigned to variable ident. You can call Set() as many times as you want.

**Comment by snizar007** [comment]
Yes, I agree that Set() can be used but the point that is being highlighted here is that REPL shell SHOULD NOT exit just because there is an error.
