### ISSUE TITLE
REPL: Inconsistent output when using `pac power-fx run` command.

### ISSUE THREAD

**Issue by snizar007** [microsoft/Power-Fx#2038]
When using simple 2 lines in text-pfx2.txt file (below) and run using `pac power-fx run --file text-pfx2.txt` results are not shown.

![image](https://github.com/microsoft/Power-Fx/assets/116691001/b7feb495-309a-42d8-bcf2-c6483f613c5d)

When I run using `pac power-fx run --file text-pfx2.txt --echo` (with --echo) results are shown.

![image](https://github.com/microsoft/Power-Fx/assets/116691001/c3a7bcb7-da8c-4c3c-bc7d-3573ae099f0b)

**Comment by anderson-joyle** [comment]
This is by design and has been answered in [another issue similar issue](https://github.com/microsoft/Power-Fx/issues/2039#issuecomment-1806319303).
