### ISSUE TITLE
REPL: Notify() function causes exit when used in a script file.

### ISSUE THREAD

**Issue by snizar007** [microsoft/Power-Fx#2039]
It seems that Notify() function is causing exit behavior when used in a Power Fx script file using `pac power-fx run --file test-pfx.txt`

test-pfx.txt file:
![image](https://github.com/microsoft/Power-Fx/assets/116691001/4919d5c0-d235-4462-8f39-ab66e361feb8)

Difference in output with and without `--echo` switch at Notify() step.

![image](https://github.com/microsoft/Power-Fx/assets/116691001/0b156b27-3b3a-47c9-a752-211bd2689f85)

**Comment by gregli-msft** [comment]
I believe this is by design.  Without --echo, all that should be shown is from Notify or from errors.  To confirm, please put another Notify after the Filter and ensure it is displayed.
