### ISSUE TITLE
REPL: Help does not need to return boolean.

### ISSUE THREAD

**Issue by snizar007** [microsoft/Power-Fx#2040]
![image](https://github.com/microsoft/Power-Fx/assets/116691001/8e53f473-af32-48d3-b953-22e4a6fc341e)

**Comment by snizar007** [comment]
![image](https://github.com/microsoft/Power-Fx/assets/116691001/3bcea322-57e9-4888-b377-e98ff57ce04b)

**Comment by MikeStall** [comment]
These can use Void type, and not return a value.

**Comment by gregli-msft** [comment]
Fixed with adding Void data type and shipped in PAC CLI 1.31.6
