### ISSUE TITLE
Office 365 Groups: Error providing date time input parameters

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#2046]
Connector documentation calls for date_time input for the action but Power Fx is expecting a record.

https://learn.microsoft.com/en-us/connectors/office365groups/#create-a-group-event-(v2)

![image](https://github.com/microsoft/Power-Fx/assets/72627659/2f5e0c7f-8ea9-43dc-9fb9-fbb602f19a23)

**Comment by LucGenetier** [comment]
![image](https://github.com/microsoft/Power-Fx/assets/69138830/cbc1e441-c6a9-4996-b24e-d2a9ffa2008a)

**Comment by LucGenetier** [comment]
From the swagger file, "start" parameter is an "object" which means we expect a record and this is what Power Apps wants too

![image](https://github.com/microsoft/Power-Fx/assets/69138830/2fc6818c-fad8-4885-ac20-6428c35dffb8)

**Comment by LucGenetier** [comment]
![image](https://github.com/microsoft/Power-Fx/assets/69138830/540276a1-7d5a-4815-903a-fcf700f92294)
