### ISSUE TITLE
Office 365 Users: Search user operation fails

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#2047]
There are a few issues with the search user operation in the office 365 users connector.

1) It has the same error as some outlook operations where it complains about the number of parameters after closing the parenthesis:

![image](https://github.com/microsoft/Power-Fx/assets/72627659/f99ccbf1-f2e5-4399-bd74-c2c7a772b0c8)

2) It prompts for skip token as input which is not a documented parameter and is not something a low code user would know what to do with:

![image](https://github.com/microsoft/Power-Fx/assets/72627659/dde11953-fa3b-40f5-b5fc-9b37b51dc0bf)

**Comment by coletaylor1** [comment]
Update profile also fails with different error

office365Users.UpdateMyProfile({aboutMe: "This is the tenant admin"}) - Error: office365Users.UpdateMyProfile failed: The server returned an HTTP error with code 400. Response: { "error": { "code": "invalidRequest", "message": "The provided encoding is not supported." } }

**Comment by coletaylor1** [comment]
Another failure

office365Users.HttpRequest("v1.0/me", "GET").displayName - Error 44-56: Name isn't valid. 'displayName' isn't recognized.

**Comment by anderson-joyle** [comment]
@LucGenetier, about this:
> It prompts for skip token as input which is not a documented parameter and is not something a low code user would know what to do with

One way to fix would this be to set `ConnectorCompatibility.SwaggerCompatibility`, but I don't know the full extension of the consequences. Is this something reasonable to suggest to Cards team?

**Comment by LucGenetier** [comment]
A valid expression for SearchUserV2 is `First(Office365Users.SearchUserV2({searchTerm: "power"}).value).UserPrincipalName`
Notice that all parameters are optional, hence Intellisense reporting 0 or 1 param for this function.

UpdateMyProfile will return 400 as the input parameters are invalid and we'll return an error - this is expected.

HttpRequest is described as returning "anything" in the swagger file ("ObjectWithoutType": {}). 
As a result, you cannot use "displayName" property
