### ISSUE TITLE
Test cases against connector's parameters versus intellisense suggestions

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#2060]
We need test cases to guarantee that the intellisense suggests arguments in accordance with what the swagger files provide in terms of parameters.

**Comment by LucGenetier** [comment]
Intellisense, by default, will follow Power Apps logic which doesn't necessarily follow swagger file exact details
- Power Apps might reorder parameters
- Non-required parameters are moved to the end of the parameter list and grouped in a(n optional) record
