### ISSUE TITLE
[Connectors] oneOf, anyOf, not, allOf are ignored

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#2076]
PowerFX doesn't handle "oneOf, anyOf, allOf, not".

Below is a simple test that demonstrates the problem (to add in OpenApiParserTests.cs)

        [Fact]
        public async Task ReturnType_ShouldUseAllOf()
        {
            using var testConnector = new LoggingTestServer(@"Swagger\CardsForPowerApps.json");
            using var httpClient = new HttpClient(testConnector);

            ConnectorFunction[] functions = OpenApiParser.GetFunctions(new ConnectorSettings("DV") { Compatibility = ConnectorCompatibility.SwaggerCompatibility }, testConnector._apiDocument).ToArray();
            var type = (RecordType)functions.First(f => f.Name == "GetCardInstance").ReturnType;
            Assert.True(type.TryGetFieldType("type", out _));
        }

**Comment by Laskewitz** [comment]
This is a OpenAPI v3 functionality which is not supported in connectors sadly.

**Comment by Robulane** [comment]
This statement is correct. Closing as not planned
