### ISSUE TITLE
[Connectors] User Agent normalization

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/Power-Fx#2111]
"x-ms-user-agent" should</span> be defined as "x-ms-user-agent": "**{team/product name}[/{product version}]** PowerFx/{version}"
Notice that 
- {team/product name} is currently missing (it's a single string)
- {product version} is optional
- the separation with "PowerFx/{version}" is a space

> [!NOTE] 
> make sure to follow RFC 9110 and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

Ex: `PVA/v12345 PowerFx/1.2.0-build.20231121-1002`

**Comment by MikeStall** [comment]
See also #2093.
