### ISSUE TITLE
Function Picker enhancements

### ISSUE THREAD

**Issue by gekarapa** [microsoft/Power-Fx#2151]
In Pad, we are currently working on implementing a function picker. To support this feature:

- [x] there's a need to extend the function info, with the localized function category names. 
- [ ] Additionally, we require a list of unique function info for each function, including a more generic description that accommodates all function's overloads.

**Comment by MikeStall** [comment]
Related to #2004

**Comment by MikeStall** [comment]
Add this:
https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Public/FunctionInfo.cs


string[] FunctionInfo.GetCategoryNames(CultureInfo locale)

**Comment by anderson-joyle** [comment]
> Additionally, we require a list of unique function info for each function, including a more generic description that accommodates all function's overloads.

This change won't be included. Hosts can group by the function name and pick one description sample to cover all overloads.
