### ISSUE TITLE
Object values are null only when imported from a component library

### ISSUE THREAD

**Issue by bananabrann** [microsoft/Power-Fx#2153]
# About

Power Apps release: **3.23123.15**
Last working version: **3.23122.20**

# Description
Last Thursday, January 11th, we were pushed a change to Power Fx / Power Apps that broke most of our component libraries. Values in my objects appear to be `null`, but only when imported from a component library. I was able to narrow the issue down to a reproducible example, and a workaround. I believe this may be a bug regarding Power Apps or Power Fx's life cycle in _when_ values are read from objects

Though both the existing and workaround code results in the exact same output in the component library's screen, the workaround involves changing where a value is read from. For example, I've found that when objects are assigned on the `OnSelect` of a button, the value (after importing) in the app will be `null` while being correct in the component library's screen. This is new behavior

At a high level, the following code ...

```
// SomeControl.OnSelect
Collect(
  myCollection,
  { prop1: value, prop2: value }
);

// Component.OutputRecord
{ prop: myCollection }
```
On **3.23122.20**,
✅ component library: works
✅ app after import: works

On **3.23123.15**,
✅ component library: works
❌ app after import: returns `[{}, {}]` (empty objects, but correctly runs `Collect()`)

At a high level, the workaround that allows the value to be read in the app involves moving where the object is built. By moving this responsibility from control's `OnSelect` to `ForAll()`, the app reads it just fine ...

```
// Control.OnSelect
Collect(myCollection, value);

// Component.OutputRecord
{ prop: ForAll( myCollection, { prop1: ThisRecord.value });

```
On **3.23122.20**,
✅ component library: works
✅ app after import: works

On **3.23123.15**,
✅ component library: works
✅ app after import: works

Even though both do the exact same thing, and are read correctly in the component library on both the new and old versions, the app fails to read the object values in the newest version

Depending on the use case of the component, it may be a bit hacky, like reading `Gallery.AllItems` with `Items = myCollection` instead of just `myCollection`, which is obviously not the best way to do things

***

Let me know if I can provide any more details or answer any questions 😎

**Comment by bananabrann** [comment]
We finally got some time with our Microsoft contractors. They're telling us this is definitely a bug, they are working on reproducing the issue

Guess I should close this issue? I don't know when to go through GitHub and when to go through Microsoft

**Comment by jorisdg** [comment]
Components are a Power Apps feature and not a language feature. You're welcome to start a support request, but our team is very active on the experimental forums when it comes to features that we are testing.
Feel free to repost here: https://powerusers.microsoft.com/t5/Power-Apps-Experimental-Features/bd-p/PA_ExperimentalFeatures and I'll point our team there to take a look.

Thanks for reporting this issue!

**Comment by bananabrann** [comment]
@jorisdg I figured as much the more and more I thought about it. Thank you for the reply 😎
