### ISSUE TITLE
Text first expression tokens

### ISSUE THREAD

**Issue by gekarapa** [microsoft/Power-Fx#2161]
To enable syntax highlighting in Pad effectively, it is crucial to distinguish between the literal string parts of the root Text first expression and those present in interpolation expressions. This distinction is necessary for addressing scenarios that demand specific (or different) highlighting for the literal string parts within the text-first expressions.
![Screenshot 2024-01-23 175542](https://github.com/microsoft/Power-Fx/assets/133134761/2f1184b7-bc27-4d77-853c-060f116996b7)

```[tasklist]
### Suggestions
- [ ] Introduce a new `TokenType`, such as `TextFirstStrLit`, to represent the string literal parts of the text-first expressions.
- [ ] Introduce TextFirstStrInterpStart and TextFirstStrInterpEnd can help mark the beginning and end of interpolation expressions.
```

**Comment by MikeStall** [comment]
Note that all this information is available through the LSP today. 

So we should see how LSP handles it, and make that lower layer public.

**Comment by anderson-joyle** [comment]
This also will cover https://github.com/microsoft/Power-Fx/issues/2155.
