### ISSUE TITLE
The JSON function cannot serialize objects of type 'UntypedObject'

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#2222]
There is no reason why we would not support this use case. Let's support it.

**Comment by MikeStall** [comment]
I agree - we should do this. 
We should be able to implement this on the existing IUntypedObject interface (without any breaking changes or extra requirements on the interface). 

Note that JSON (ParseJson()) does not necessarily round trip.

**Comment by newmanjt** [comment]
Hello! I am currently attempting to go from Table to Text without success without Power-Fx in Copilot. 

`JSON(Topic.result,JSONFormat.IgnoreBinaryData & JSONFormat.IgnoreUnsupportedTypes)`

Receiving this error: The JSON function cannot serialize objects of type 'Table'.

Appreciate any update!

**Comment by PabloRoldanCRM** [comment]
Will this going to be in public MS Copilot?

if you try to do JSON(Topic.Var1, JSONFormat.IgnoreUnsupportedTypes) "The JSON function cannot serialize objects of type table"

So it works if you do that inline e.g. JSON(["1","2"]) but if you store ["1",""2"] in a variable it wont work

**Comment by mdrichardson** [comment]
@PabloRoldanCRM, this was fixed in [this PR](https://github.com/microsoft/Power-Fx/pull/2743). I'm working on the update to Copilot Studio, now. I'd expect it to hit production in early January.
