### ISSUE TITLE
REPL: [pac pfx] Error: Too many entities in table team, more than 1000 rows

### ISSUE THREAD

**Issue by bnc-cvx** [microsoft/Power-Fx#2250]
I would like to use `pac power-fx` in some scripting. I'm running into a problem where I try to use the Lookup formula to retrieve a Dataverse Team by name:
```
LookUp(team, name = "my-team-01")
```
I've tried to use this formula with both `pac pfx run --file` and from `pac pfx repl` and both result in the same error:
![<Error: Too many entities in table team, more than 1000 rows>](https://github.com/microsoft/Power-Fx/assets/139287163/4908631b-f59b-437e-947c-275a67a30bf2)

Would really like for this to be resolved so we can utilize Power Fx as part of our scripting strategy.

**Comment by MikeStall** [comment]
It looks like we're missing a call to EnableDelegation() in repl.  Will add.

**Comment by gregli-msft** [comment]
This should be fixed with the recently released PAC CLI 1.31.6.  Please confirm, and if not, let us know.
