### ISSUE TITLE
Suggestions function to REPL

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#2313]
Add a new `Suggestions` (or any better name) pseudo function to display engine suggestions, making use of the cursor pointer (`|`).
Examples can be found here:
https://github.com/microsoft/Power-Fx/blob/ed83c6709c8e633a999ac0b186951d2162be7e6e/src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs#L193

**Comment by LucGenetier** [comment]
https://github.com/microsoft/Power-Fx/pull/2023
