### ISSUE TITLE
Text(DateValue(Today()), "") Doesn't Return Today's Date in Unix Time

### ISSUE THREAD

**Issue by yunhapark97** [microsoft/Power-Fx#2376]
Hi! Cards team has been running into issues when executing `Text(DateValue(Today()), "")` expression in Cards.

The same expression returns Today's date in Unix time in Canvas:

![image](https://github.com/microsoft/Power-Fx/assets/142846149/5a5324e2-22a9-4d22-8d86-a5c819995adb)

whereas an empty string ("") gets returned in Cards:

![image](https://github.com/microsoft/Power-Fx/assets/142846149/22e2d19a-b2b0-4758-82b3-1ac1c5caf8e0)

![image](https://github.com/microsoft/Power-Fx/assets/142846149/cfb659d7-57e6-4e55-b366-2d17a6eb87ed)

Any insights or guidance on this issue would be greatly appreciated. Thanks a lot for your time and help in advance!

**Comment by anderson-joyle** [comment]
This expression should give you the wanted result:
`Round((Now() - DateTime(1970,1,1, 0,0,0) ) * 86400000, 0)`

You can replace `Now()` with another datetime value.
