### ISSUE TITLE
Deprecated functions should not be skipped

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#2419]
OpenApiParser.GetFunctions method should return deprecated functions or have a parameter that will instruct to return the deprecated functions.

**Comment by LucGenetier** [comment]
Using Office 365 Outlook swagger file

            IEnumerable<ConnectorFunction> f2 = OpenApiParser.GetFunctions("Office365Outlook", apiDoc, new ConsoleLogger(_output));
            Assert.Equal(43, f2.Count(f => f.IsDeprecated));

**Comment by LucGenetier** [comment]
Same with

            IEnumerable<ConnectorFunction> f2 = OpenApiParser.GetFunctions(new ConnectorSettings("Office365Outlook") { Compatibility = ConnectorCompatibility.SwaggerCompatibility }, apiDoc, new ConsoleLogger(_output));
            Assert.Equal(43, f2.Count(f => f.IsDeprecated));
