### ISSUE TITLE
Get a list of all called functions in an expression 

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#2455]
New API to get a list of all called functions in an expression. Maybe `ParseResults.GetListOfCalledFunctions()`.
Expression: `With({x:Abs(First(table).field)}, Abs(x-y))`
Result: ["With", "Abs", "First", "Abs"]

**Comment by MikeStall** [comment]
This should hang off CheckResult, similalar to TopLevelIdentiifers. 

If we just want function names, we can get from parser:

IEnumerable<string> CheckResult.GetFunctionNames()
Very similar to what we already do with TopLevel identifiers. 
This can succeed after ApplyParse() and skip binding. 


If we want binding... we should return these: 
https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Public/Reflection/FunctionInfo.cs

IEnumerable<FunctionInfo> CheckResult.GetFunctions()
