### ISSUE TITLE
TimeZoneOffset() returns incorrect value for "Central European Standard Time"

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#2480]
TimeZoneOffset() should currently return `-60` for `Central European Standard Time`, but returns `-120`
https://fx4.azurewebsites.net/?session=t1#expr_VGltZVpvbmVPZmZzZXQoKQ==
![image](https://github.com/microsoft/Power-Fx/assets/32079188/84e51361-67e8-4e1b-86f4-32d760c4fd9d)

**Comment by LucGenetier** [comment]
This seems normal
Am I missing anything?

![image](https://github.com/microsoft/Power-Fx/assets/69138830/e67dafcd-19e1-402e-bae6-f23fc6ea8f34)
