### ISSUE TITLE
Throwing Meaningful exception when Decoding Response fails

### ISSUE THREAD

**Issue by greedyaj** [microsoft/Power-Fx#2523]
We are consuming the function `Microsoft.PowerFx.Connectors.ConnectorFunction.InvokeAsync(.. `
This function upon failure to decode response returns System.NotImplementedException,
`System.NotImplementedException: Expecting a TableType Json Array but got Record`

This exception is very generic and does not help us handle this error well in our product.

Please create a new specific exception which will indicate what went wrong in this call.

**Comment by MikeStall** [comment]
Is the request to implement this case?

**Comment by greedyaj** [comment]
yes, please
cc: @LucGenetier
