### ISSUE TITLE
CLI Issue

### ISSUE THREAD

**Issue by nathanroseakl** [microsoft/Power-Fx#2573]
Hi - I'm noticing an issue I can't explain when using the Power Fx CLI. 

I'm generating a dynamic table of dates using the following expression

ForAll(Sequence(DateDiff(Date(2024,8,1),DateAdd(Date(2024,8,31),1))), DateAdd(Date(2024,8,1),Value))

When I run the expression the first date in the range {'Date(2024,8.1)} isn't included in my table. Am I doing something wrong? 

I've attached a screenshot of the output in the CLI
![2024-08-05 17_33_35-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/a48b1b12-6c10-456d-8705-0a9e96ac1129)

**Comment by nathanroseakl** [comment]
Update on this - I added an add'l DateAdd(),-1 which resolved the issue - question is in the orig screenshot is that expected behaviour? 
![2024-08-05 17_51_20-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/88c77af7-0455-4bed-9cad-dcd3effe328f)
![2024-08-05 17_33_35-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/644fddcd-33df-4b9e-babd-b710a9648e1d)
[Pre-SET (1).pdf](https://github.com/user-attachments/files/16491277/Pre-SET.1.pdf)

**Comment by anderson-joyle** [comment]
The `Sequence` function starts at 1 by default. 
![image](https://github.com/user-attachments/assets/55f32ce4-3182-4a70-8c09-6e8184c60cbd)

If you want a zero-based sequence, you can pass the [optional arguments](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-sequence#syntax):
`Sequence(10,0,1)`
![image](https://github.com/user-attachments/assets/8338214b-b3a7-4540-9769-7e51af251613)


It makes sense that the first element of your expression is `Date(2024,8,2)`.

Let me know if this answers your question and if it does, please close the issue.

**Comment by nathanroseakl** [comment]
Hi Anderson, thanks for that - I did some more investigating and it appears the issue is localised to the month of September - have attached some screenshots - would this be related to Sequencing or something else?
![2024-08-06 16_41_26-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/919d4873-572c-4650-a268-25c1fe5009d9)
![2024-08-06 16_40_59-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/03c59cd5-4a87-4cfd-be02-8899d23cbefb)

**Comment by nathanroseakl** [comment]
Hi Anderson - I've updated my expression to stipulate the Sequence start point and it works for all months EXCEPT September - it's really weird - screenshots below. 

Here's my expression for September (all other months are exactly the same with the exception of the month value) ForAll(Sequence(DateDiff(Date(2024,9,1),DateAdd(Date(2024,9,30),1)),0), DateAdd(Date(2024,9
![2024-08-06 17_03_40-● ForAll(Sequence(DateDiff(Date(2024,8,1), • Untitled-1 - desktop-tutorial - Vis](https://github.com/user-attachments/assets/59c2f202-59c4-4a96-b5b2-f4701b60d7f9)
,1), Value))

**Comment by nathanroseakl** [comment]
Closing this - looks like it's a Daylight Savings related issue H/T to James Williams for this one 

This is his code snippet 

With({startDate:Date(2024,9,1),endDate:Date(2024,9,30)},ForAll(Sequence(DateDiff(startDate,endDate)+1+Value(TimeZoneOffset(startDate)>TimeZoneOffset(endDate))),DateAdd(startDate,Value-1)))
