### ISSUE TITLE
IfError function bug

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#2604]
It seems that `IfError` function is trying to convert `arg1` into `arg0` type.

Expression: `IfError(1/0, FirstError.Message)`
Result: `<Error: The value 'Invalid operation: division by zero.' cannot be converted to a number.>`

**Comment by CarlosFigueiraMSFT** [comment]
That's by design. The type of IfError is the type of the last possible "positive" result (the 1st / 3rd / 5th / ... arguments)

**Comment by anderson-joyle** [comment]
Ok. So I think if we want to catch the error message in an expression similar to the description, we would need something like `IfError(1/0;"dummy string", FirstError.Message)`

**Comment by CarlosFigueiraMSFT** [comment]
You can also use a simpler text expression in the first argument: `IfError(Text(1/0), FirstError.Message)`

**Comment by anderson-joyle** [comment]
Thanks for clarifying. Closing the issue since this is by design.
