### ISSUE TITLE
Filter should be able to handle empty rows

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [microsoft/Power-Fx#263]
These expressions should return a table with 5 elements. Today they don't (the first one does not work, the second one removes the empty record):

- Filter(Table({a:1},{a:2},If(1<0,{a:3}),{a:4},{a:5}), true)
- Filter(Table({a:1},{a:2},If(1<0,{a:3}),{a:4},{a:5}), IsBlank(a) Or a > 0)

**Comment by anderson-joyle** [comment]
This is the solution I found for the second expression.
Microsoft.PowerFx.Interpreter > Functions > LibraryTable > method LazyFilterRowAsync:

            SymbolContext childContext;

            if (row.IsValue)
            {
                childContext = context.WithScopeValues(row.Value);
            }
            else if (row.IsBlank)
            {
                childContext = context.WithScopeValues(RecordValue.Empty());
            }
            else
            {
                return null;
            }

            // Filter evals to a boolean 
            var result = await filter.EvalAsync(runner, childContext);
            var include = false;
            if (result is BooleanValue booleanValue)
            {
                include = booleanValue.Value;
            }
            else if (result is ErrorValue errorValue)
            {
                return DValue<RecordValue>.Of(errorValue);
            }

            if (include)
            {
                return row;
            }

            return null;`

This code worked for all my manual tests using the [Power Fx host samples](https://github.com/microsoft/power-fx-host-samples). Next step would be adding testing cases to this fix into [ExpressionTestCases](https://github.com/microsoft/Power-Fx/tree/main/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases). Once I've tested everything from my end I'll push a change request.

About the first expression on this issue, I'll start to work on it very soon.

**Comment by MikeStall** [comment]
Resolved with #293 , Thanks @anderson-joyle !
