### ISSUE TITLE
Hostability in .net

### ISSUE THREAD

**Issue by aL3891** [microsoft/Power-Fx#28]
I've been generally uninterested in the power platform since from what i understand, it's only available as a hosted product from microsoft, meaning that any apps written in it is locked in to online use/hosting with Microsoft. This is absolutely fine for some projects mind you, just not something that has been applicable to the things i'm working on

However from what i understand Powerfx will eventually be open source and available to any application. will it be hostable inside a .net app for example? What about language services, for statement completion and syntax highlighting, will that also be available? WIll a host application be able to get an AST (similar to roslyn for example) to analyze the Powerfx code?

I can see Powerfx as a useful tool to expose some high level query functionality in our internal apps,

**Comment by jgrisham** [comment]
I would not expect any tools released in the near future - summary here: 

> https://github.com/microsoft/Power-Fx/issues/8#issuecomment-841596355

**Comment by aL3891** [comment]
Perhaps, though in this [build talk](https://mybuild.microsoft.com/sessions/277e7de0-5d66-4b56-a18e-cfd6d50736e7) they discuss releasing the host and formula bar as components 
see around the 20 minute mark for example

**Comment by MikeStall** [comment]
The source is now live and we've added samples for hosting here: https://github.com/microsoft/power-fx-host-samples
