### ISSUE TITLE
Unable to use daily build feed

### ISSUE THREAD

**Issue by rajyraman** [microsoft/Power-Fx#299]
When I try to use the Nuget feed for [daily build](https://github.com/microsoft/Power-Fx/blob/main/dailyBuilds.md), I get a SSL error.

![image](https://user-images.githubusercontent.com/5035266/163076041-a0e603e4-eb31-49a6-8a62-3c694389678c.png)

**Comment by BruceHaley** [comment]
Hi Natraj,
Are you still having this problem?
If so, can you please provide a step-by-step description of how to reproduce it. Please include OS, sample project if any, tools, etc.
Also, can you try downloading the .nupkg file by hand: Go here https://dev.azure.com/ConversationalAI/BotFramework/_artifacts/feed/SDK/NuGet/Microsoft.PowerFx.Transport.Attributes/0.2.1-preview.20220412-300058/overview and click the Download button.
Thank you.
--Bruce

**Comment by MikeStall** [comment]
@rajyraman - that looks like a networking issue (SSL Warnings). Is this still an issue?

**Comment by rajyraman** [comment]
@BruceHaley @MikeStall - I still cannot add the package via LINQPad, but I can download the nupkg file via browser.
