### ISSUE TITLE
Missing Unary Negate

### ISSUE THREAD

**Issue by jcdickinson** [microsoft/Power-Fx#30]
The unary negate seems to work in Power Apps:

![image](https://user-images.githubusercontent.com/522465/125878183-917b341f-ce73-4db2-bdc1-cec7c3759cd9.png)

There is no unary negation in the expression grammar.

**Comment by MikeStall** [comment]
It's definitely present in the code: https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Syntax/Nodes/UnaryOpNode.cs 

Is this just missing from the grammar?

**Comment by jcdickinson** [comment]
Yes, at the time I opened this issue there was no code.
