### ISSUE TITLE
Support for Behavior properties

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#301]
Allow the semicolon chaining operator and behavior properties, for example: `A;B;C` 
This is just meaningful for behavior function (Side-effecting). 

- [ ] This requires a special flag to parser (AllowExpressionChaining ) to accept semicolons. 
- [ ] Clean public surface area, (may be related to https://github.com/microsoft/Power-Fx/pull/272 and https://github.com/microsoft/Power-Fx/pull/294 ) 
- [ ] Flow through binding 
- [ ] Support in the IR and Interpreter so it can be evaluated. 
- [ ] How do user defined functions (ie, reflectionFunction) specify they're a behavior function. 
- [ ]  ensure RecalcEngine can't set a formula to a behavior property

**Comment by LucGenetier** [comment]
#322
