### ISSUE TITLE
Mod() results are wrong for negatives

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#304]
Fx is not implementing Mod() properly (consistently with Excel) for negative numbers. 

Here are some test cases that should pass  (add as a new file, mod.txt in https://github.com/microsoft/Power-Fx/tree/main/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases, and then run via this test: https://github.com/microsoft/Power-Fx/blob/fe0f1bd053497d2a53ca23ea188647ab104b2f94/src/tests/Microsoft.PowerFx.Interpreter.Tests/FileExpressionEvaluationTests.cs#L24 ) 

```
>> Mod(-456,1)
0

>> Mod(-456,15)
9

>> Mod(3456,-1)
0

>> Mod(3456,-2)
0

>> Mod(3456,-11)
-9

>> Mod(-3456,-1)
0

>> Mod(-3456,-2)
0

>> Mod(-3456,-11)
-2

>> Mod(14.123456,1)
0.123456

>> Mod(14.123456,3)
2.123456

>> Mod(14.123456,-2)
-1.876544

>> Mod(-14.123456,-18)
-14.123456

>> Mod(14.123456,0.123)
0.101456

>> Mod(-14.123456,3.678)
0.588544

>> Mod(-1412.34,-2.9)
-0.04

```

**Comment by anderson-joyle** [comment]
This is a tricky one.
From my tests, PFx implements the mod() function as it should be. It passes the two values to the framework itself and simply returns the result. Any other application written in .NET should produce the same outcome.
There is this [article](https://www.geeksforgeeks.org/modulo-operations-in-programming-with-negative-results/) explaining how different programming languages implement the Euclidean division concept.

I am assuming Excel implements the mod() function in a different way than PFx (.NET).

There following code (roughly written) passes on all test cases of the mod.txt file:
https://github.com/microsoft/Power-Fx/blob/e2ffacc79cd57a2f5b9a30cc05c41460d3478fb0/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs#L441

```
public static FormulaValue Mod(IRContext irContext, NumberValue[] args)
{
    var arg0 = args[0].Value;
    var arg1 = args[1].Value;

    // r = a – N × floor(a/b)
    var q = (int)Math.Floor((double)arg0 / arg1);
    var result = arg0 - (arg1 * q);

    return new NumberValue(irContext, result);
}
```

Not sure if this would be the solution though. It seems I'm "overwriting" the native way of how the framework calculates the modulo.

Looking forward to hear your comments on this.

**Comment by MikeStall** [comment]
_"I am assuming Excel implements the mod() function in a different way than PFx (.NET)."_ That's exactly correct - that's the bug here.  But Power Fx is supposed to behave like Excel, so we have a clear winner for what we ought to be doing.  It's just the original implementation of Mod just naively called .Net's function without thinking about the corner case issues. 

The fact that Power Fx is implemented on C# shouldn't dictate the Power Fx semantics. This is important because we have Power Fx implementations for running on JScript and SQL too - so the underlying codegen shouldn't dictate the public semantics. The semantics are locked (per excel) and we adjust our codegen to match. 

Would you submit a PR with the fix? Thanks for looking!

**Comment by anderson-joyle** [comment]
I got your point. Thanks for taking the time to explain it.
PR #307 has been submitted.
