### ISSUE TITLE
Open source timeline?

### ISSUE THREAD

**Issue by stde-epro** [microsoft/Power-Fx#32]
The overview for Power-Fx states: 
> Power Fx will be made available as open-source software. It's currently integrated into canvas apps, where you can experience it today. We're in the process of extracting it from Power Apps for use in other Microsoft Power Platform products and as open source. More information: Microsoft Power Fx on GitHub

https://docs.microsoft.com/en-us/power-platform/power-fx/overview

I have questions

- [ ] Is there a timeline for this?
- [ ] Which OSS licence?   

I note F# and VSC are MIT-licenced and TypeScript is Apache2

**Comment by ApolonTorq** [comment]
I have the same question as its coming up to six months from the initial announcement. Even early/incomplete source code and confirmation of the license applied would be useful. Thanks.

**Comment by orcmid** [comment]
See issue #8 for discussion of what is exactly being open-sourced.

Issue #13 is also relevant.

It appears that this issue duplicates these.  Issue #15 is in there also.

I have seen the message from @gregli-msft at Discussion #2.  There are currently 7 open (i.e., dangiing) pull requests from March-May.   It is easy to get the feeling that nobody's home. :).

**Comment by fabiofranzini** [comment]
Please check the repo now... 👍

**Comment by MikeStall** [comment]
Timeline is 6 am today! Here's the announcement: https://powerapps.microsoft.com/en-us/blog/power-fx-open-source-now-available/

It's an MIT license.
