### ISSUE TITLE
Choice option is not updated in Power Fx (in Command Bar editor)

### ISSUE THREAD

**Issue by vincenty934** [microsoft/Power-Fx#33]
When using the Power Fx formula to set the visibility of a Command (in the new Command Bar editor), I realized that a newly added option in the Choice did not show up in  Formula bar.  Even after I have published all the customization.  The option is visible in the Custom Page formula bar.   Please see the attached screenshot below.
![image](https://user-images.githubusercontent.com/82472121/134565661-ee7d234c-6eb1-4c46-973d-72ec94c4611a.png)
![image](https://user-images.githubusercontent.com/82472121/134565709-61129155-2902-4a18-9d47-c1f4ca17f875.png)
![image](https://user-images.githubusercontent.com/82472121/134565751-7c7b29aa-4d8c-48ef-a985-6de86dfb04b8.png)

**Comment by davidyack** [comment]
You probably need to open the component in the solution and refresh the data source for the table.

**Comment by vincenty934** [comment]
I have checked everywhere In the Command Bar Editor, there is no data source option to refresh.  I also check the solution and see if the data source refresh available there but so far no luck.

**Comment by vincenty934** [comment]
Found the solution.  I need to refresh the data source in the Component Libraries (save and publish) in order to get the Power Fx formula pickup the newly added option.  

![image](https://user-images.githubusercontent.com/82472121/134682323-3b749d0f-070f-4af2-8309-b53ec723ea1f.png)
