### ISSUE TITLE
System.NotSupportedException : Specified method is not supported in RecalcEngine.Check

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#336]
The following test fails with System.NotSupportedException. It should not fail but return the errors in result object.
      
        [Fact]
        public void CheckSuccess2()
        {
            var config = new PowerFxConfig();
            var engine = new RecalcEngine(config);

            var result = engine.Check(
                "T.Var = 23",
                new RecordType()
                .Add(new NamedFormulaType("T", new RecordType()
                    .Add(new NamedFormulaType("Var", FormulaType.String))))
                .Add(new NamedFormulaType("G", new RecordType().Add(new NamedFormulaType("var2", FormulaType.Number)))));

            Assert.False(result.IsSuccess);
        }

**Comment by MikeStall** [comment]
And the failure is comparing T.Var (a string) to 23 (a number)

**Comment by MikeStall** [comment]
Simpler repro: 

        [Fact]
        public void CheckSuccess3()
        {
            var config = new PowerFxConfig();
            var engine = new RecalcEngine(config);

            var result = engine.Check("\"abc\" = 23");
            Assert.False(result.IsSuccess);
        }

Exception is coming from IR translator here: 
https://github.com/microsoft/Power-Fx/blob/d79caebb206926d6a91c61404648975631cb99de/src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs#L840

**Comment by MikeStall** [comment]
In a canvas app, this runs but returns a warning:
![image](https://user-images.githubusercontent.com/1538900/164767279-ccf11a6b-5d19-46b9-b6ca-2f66449dd6fd.png)

**Comment by MikeStall** [comment]
Excel does allow this. So it should stay a warning. IR should just return constant false node. 
![image](https://user-images.githubusercontent.com/1538900/164768741-603a8eab-6c31-4fff-a224-048e2718e081.png)

**Comment by MikeStall** [comment]
This was likely regressed with https://github.com/microsoft/Power-Fx/pull/306

Before, warnings were errors - and that would have blocked the IR from even attempting to translate. 
Now we allow warnings and so the IR is running and hitting a missing case.
