### ISSUE TITLE
function call optimization 

### ISSUE THREAD

**Issue by pseudolus** [microsoft/Power-Fx#34]
Some functional languages with immutable data support an optimization where a function calls with identical arguments will only be called once and the return value is cached.

Is that currently a feature of Power-fx?  Or is it planned?

**Comment by tjohnston-fcg** [comment]
Answered my own question, output properties on a component accomplish this purpose.  It would be nice to see the language keep this ability as it evolves to support more than canvas apps.

**Comment by pseudolus** [comment]
Answered my own question, output properties on a component accomplish this purpose. It would be nice to see the language keep this ability as it evolves to support more than canvas apps.
