### ISSUE TITLE
Sample for Host Integration incl custom functions.

### ISSUE THREAD

**Issue by tthiery** [microsoft/Power-Fx#36]
Many of us build LOB no-code platforms. Can we have a sample showing how to integrate the open sourced libraries into our products, especially:

- Hosting the interpreter
- How to load custom functions
- How to provide custom variable / value providers (like a sheet references or object trees etc)

This libraries look awesome!

---

tl;dr: The team meanwhile update the README with a link to the [samples](https://github.com/microsoft/power-fx-host-samples)

**Comment by fabiofranzini** [comment]
Thanks @tthiery for opened this issue! 👍

**Comment by fabiofranzini** [comment]
Hi @tthiery, this is a quite simple implementation on how to evaluate formula using c#.

```csharp
using System;
using Microsoft.PowerFx;
using Microsoft.PowerFx.Core.Public.Types;
using Microsoft.PowerFx.Core.Public.Values;

namespace Apvee.PowerFx.Console {
  class Program {
    static void Main(string[] args) {
      var simpleFormula = "A + 3 + B + B";
      var filterFormula = "Filter(Accounts; Age>30)";

      var engine = new RecalcEngine();

      var accountType = new TableType()
        .Add(new NamedFormulaType("Age", FormulaType.Number))
        .Add(new NamedFormulaType("Name", FormulaType.String));

      var contextType = new RecordType()
        .Add(new NamedFormulaType("A", FormulaType.Number))
        .Add(new NamedFormulaType("B", FormulaType.Number))
        .Add(new NamedFormulaType("Accounts", accountType));

      var context = FormulaValue.NewRecord(new {
          A = 2,
          B = 5,
          Accounts = new [] {
            new {
              Age = 31, Name = "User 1"
            },
            new {
              Age = 29, Name = "User 2"
            },
            new {
              Age = 33, Name = "User 3"
            }
          }
      });

      var simpleCheck = engine.Check(simpleFormula, contextType);
      if (simpleCheck.IsSuccess) {
        var simpleResult = engine.Eval(simpleFormula, context);
        System.Console.WriteLine(simpleResult.ToObject().ToString());
      }

      var filterCheck = engine.Check(filterFormula, contextType);
      if (filterCheck.IsSuccess) {
        var filterResult = engine.Eval(filterFormula, context);
        System.Console.WriteLine(filterResult.ToObject().ToString());
      }
    }
  }
}
```
This implementation is in the early-stage phase, I think. 
I didn't find anything regarding the state management.

**Comment by MikeStall** [comment]
We are adding samples at: https://github.com/microsoft/power-fx-host-samples
It currently has just a repl. 

Some of these examples are also via the unit tests: https://github.com/microsoft/Power-Fx/blob/main/src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs

**Comment by fabiofranzini** [comment]
Another example on using the state management (found by made some tests):
 ```csharp
using System;
using Microsoft.PowerFx;
using Microsoft.PowerFx.Core.Public.Types;
using Microsoft.PowerFx.Core.Public.Values;

namespace Apvee.PowerFX.Console
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = new RecalcEngine();

            var contextType = new RecordType()
                .Add(new NamedFormulaType("A", FormulaType.Number))
                .Add(new NamedFormulaType("B", FormulaType.Number));

            var context = FormulaValue.NewRecord(new
            {
                A = 1,
                B = 5
            });

            engine.UpdateVariable("context", context);
            engine.SetFormula("result", "context.A * context.B", null);
            System.Console.WriteLine(engine.GetValue("result").ToObject().ToString());

            context = FormulaValue.NewRecord(new
            {
                A = 3,
                B = 5
            });

            engine.UpdateVariable("context", context);
            System.Console.WriteLine(engine.GetValue("result").ToObject().ToString());
        }
    }
}

 ```

**Comment by fabiofranzini** [comment]
@MikeStall Is PowerFx completely based on .NET Core or are you planning to release an engine for JavaScript too?

**Comment by fabiofranzini** [comment]
> @MikeStall Is PowerFx completely based on .NET Core or are you planning to release an engine for JavaScript too?

Ok, the timeline it's clear now... https://powerapps.microsoft.com/en-us/blog/power-fx-open-source-now-available/
I think that the Js implementation is very important!

**Comment by MikeStall** [comment]
@fabiofranzini  - We have a common front-end (parsing, binding, semantics, Intermediate Representation) and then multiple backends. 

- We've open sourced a C# interpreter implementation here. 
- Power Apps Canvas apps uses a JScript runtime - but that isn't open source yet. 
- Dataverse formula columns actually uses a SQL backend! (https://powerapps.microsoft.com/en-us/blog/power-fx-formula-columns-in-dataverse/) 

We plan to make this more open and extensible to enable more backends in the future.

**Comment by MikeStall** [comment]
The current binding for objects into Power Fx requires fully copying the object - so that does not scale to large tables. We do have plans to fix this and essentially add the delegation abilities ( https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview ) to the implementation here.

**Comment by fabiofranzini** [comment]
@tthiery I think that, with the current implementation here (.net standards), it's possible to execute the interpreter in wasm mode (using for example blazor).

Looking forward for the js implementation ❤️

**Comment by tthiery** [comment]
@MikeStall thanks for the clarification. That is exactly my worry. I have prototyped calculation systems with external reference and data models (ensuring topological sorting and data lookups). But at a certain point I was out of luck, time and mood when it came to determine executions instances etc. Curious how this will work here.

**Comment by MikeStall** [comment]
@tthiery - right, Delegation is very similar to linq.

**Comment by tthiery** [comment]
Thanks for the conversation!

**Comment by rajyraman** [comment]
> We are adding samples at: https://github.com/microsoft/power-fx-host-samples It currently has just a repl.
> 
> Some of these examples are also via the unit tests: https://github.com/microsoft/Power-Fx/blob/main/src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs

@MikeStall - Is it possible to surface these custom functions back to either Power Apps canvas app, Ribbon or calculated column, or is this restricted entirely to the custom application using Power Fx framework?

**Comment by MikeStall** [comment]
@rajyraman - The custom functions here are currently just for hosts that host the power fx engine themselves. 

We do have a preview of component story for Power Apps which lets you effectively create your own functions - see https://powerapps.microsoft.com/en-us/blog/enhanced-component-properties/ for more details.

**Comment by matthewdevaney** [comment]
@MikeStall
If we submit custom functions this repo as @rajyraman mentioned will they be considered by the development team for inclusion in the Power FX langauge?

Certainly we don't want to see Power FX filled with 100s of functions which are not used often.  But there are several functions missing from the MS Excel language I'd like to try my hand at contributing

Examples:
CEILING
EOMONTH
FLOOR
LARGE
ROMAN
SMALL
