### ISSUE TITLE
Nuget for better dataverse integration

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#369]
Provide a shared nuget to aide in power fx calling Dataverse.
Specifically have these functions:

EntityMetadata --> RecordType
Entity  + EntityMetadata  --> RecordValue

Likely depend on this .net core nuget:
https://www.nuget.org/packages/Microsoft.PowerPlatform.Dataverse.Client

**Comment by MikeStall** [comment]
We have a preview of this ready.

**Comment by MarkMpn** [comment]
@MikeStall Are you able to share this preview please?
