### ISSUE TITLE
`Concat` implementation doesn't offer separator optional argument

### ISSUE THREAD

**Issue by jjkinsey** [microsoft/Power-Fx#38]
This implementation of the `Concat` function doesn't accept the optional "Separator" argument [specified in the documentation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-concatenate#syntax)/that exists in Power Apps:

https://github.com/microsoft/Power-Fx/blob/06d8a10afb10ecd4d194b3537fc925ade64b8c43/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs#L27-L49

It looks like this is related to the general implementation of functions with optional arguments/multiple different sets of arguments, inspecting the implementation of some of the [aggregate numerical functions](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-aggregates) like `Average`: 

https://github.com/microsoft/Power-Fx/blob/06d8a10afb10ecd4d194b3537fc925ade64b8c43/src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs#L47-L71

So, perhaps this issue can be used to track improvements to the function dispatch implementation? (Would this be [multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch)?)

**Comment by anderson-joyle** [comment]
Separator arg is now available.
