### ISSUE TITLE
Implement Power FX for Power Platform Calculated Columns

### ISSUE THREAD

**Issue by Xisrith** [microsoft/Power-Fx#39]
Currently Calculated Columns only offer a very small subset of the functions available to canvas apps. Ideally they would support the full array of functions available, but in this issue I can only give the concrete example I've run into:

Problem: Calculate the number of days from today to some date, called `StartDate`
Formula listed in MSDN: `DiffDays(StartDate, NOW())`
Error: `NOW()` returns a DateTime, while `StartDate` returns a Date, DiffDays is unable to resolve these different types

Possible solutions, using Power FX formulas:
1. Use the `TODAY()` method instead of `NOW()` so both data types are Dates
2. Use one of the various methods available to either:
    a. Create a DateTime object from `StartDate`
    b. Create a Date object from `NOW()`

Note: None of the methods mentioned above are currently available in calculated columns

**Comment by MikeStall** [comment]
Because calculated columns are running on the server, we're using UtcToday(), UtcNow() functions.

**Comment by MikeStall** [comment]
More on formula columns: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns?tabs=type-or-paste
