### ISSUE TITLE
Async functions

### ISSUE THREAD

**Issue by faramos** [microsoft/Power-Fx#40]
Awesome job!

Will Power-Fx support asynchronous functions?

**Comment by faramos** [comment]
I´m evaluating powerfx and adaptive-expressions as an alternative to javascript for a low-code platform, but we depend on execute functions that returns Promises/Task.

```
private class TestAsyncFunction : ReflectionFunction
        {
            public TestAsyncFunction () : base("TestAsync", FormulaType.Boolean) { }

            public Task<BooleanValue> Execute()
            {
                //...
```

**Comment by MikeStall** [comment]
We will support that. Stay tuned...

**Comment by MikeStall** [comment]
Getting closer. Support added in: 
https://github.com/microsoft/Power-Fx/pull/247
https://github.com/microsoft/Power-Fx/pull/261

Now we just need to expose registering a custom async function. (interfaces are still internal)
