### ISSUE TITLE
Way to Retrieve all Formulas from RecalcEngine

### ISSUE THREAD

**Issue by zane-woodard-drc** [microsoft/Power-Fx#41]
I may have missed something, but there doesn't appear to be a way to get a list of all defined formulas/variables back from the RecalcEngine. I see that the value can be retrieved if you have the name, but this would require the PowerFx-consuming application to remember the names of all formulas/variables.

I believe this would be useful for many reasons, but the two initial use cases I've come across that couldn't be addressed due to this missing are:

* Showing the user everything currently defined, so they don't need to remember everything they've set so far
* Dumping all formula values, serializing them, saving them somewhere persistent, and later retrieving + redefining the formulas so that a user can resume their "session" from much earlier without needing to keep RecalcEngine alive the entire time

**Comment by MikeStall** [comment]
Here's where the list of formulas is stored: 
https://github.com/microsoft/Power-Fx/blob/4b8a3e1e7bbe48f7e5870367cebbaaea10d633f7/src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs#L21

So this would be exposing something on the RecalcEngine test. 

And then adding a unit test here: 
https://github.com/microsoft/Power-Fx/blob/main/src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs

**Comment by anderson-joyle** [comment]
You can also get a mutable list of functions if you want to restrict the usage of some of them.
https://github.com/microsoft/Power-Fx/blob/dce024a2096f80a211ba9c59f95fa48093ccbf72/src/tests/Microsoft.PowerFx.Core.Tests/SymbolTableTests.cs#L190C52-L190C52
