### ISSUE TITLE
-The Quantum Rift

### ISSUE THREAD

**Issue by deonlewisduke** [microsoft/Power-Fx#424]
Where do we begin? At the end? We have a solidary trapped Quantum network and then we have the open Quantum network "the sum of all other devices".

If 0 is the whole, than 1 is less then 0. If all of math is 0's or 1's adds and takes away. The 0 is with out a positive or negative that which remains and stays, the whole. Now you are all trying to superposition or be in the trapped & the open simultaneously: hence my code.

Zero.Var = is there anything else?
If not then run code. If so *.var.

'Would you like to know more?'

**Comment by MikeStall** [comment]
@deonlewisduke  - can you clarify the question?

**Comment by deonlewisduke** [comment]
"Are you attempting to create a language/cmd/code/program system-of-control and manipulation (call it what you will) that affects all approximately 3 billion devices, (come what may) in a manner that anyone of us 8 billion morons can access to wits against or fore the wiles of formerly known as 'Cortana' or #tbd the thing in the Quantum box?"

Get OPTION devices for the SOLID web!
