### ISSUE TITLE
Round() doesn't always round

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#488]
Tried on the [sample app](https://github.com/microsoft/power-fx-host-samples) and spotted floating point problem for `Round()`. 

```
> Round(10.2, 1)
10.200000000000001

> Round(0.3,1)
0.30000000000000004
```

I can repro for `RoundUp` and `RoundDown` too.
```
> RoundUp(0.3,1)
0.30000000000000004

> RoundDown(0.31,1)
0.30000000000000004
```

**Comment by MikeStall** [comment]
Fixed by #499
