### ISSUE TITLE
Boolean(true) shouldn't be invalid

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#489]
Type conversion typically allow a value to convert to its current type. Looks like Power FX allows that for `Value` and `Text`, but not `Boolean`:

`Value(10)` returns `10`
`Text("hello")` returns `"hello"`

But
`Boolean(true)` is invalid.

This feels like a bug to me. Thoughts?

**Comment by MikeStall** [comment]
Curious - what sort of scenario does this come up?

**Comment by susosuso** [comment]
it's just more of an inconsistency to me. Say if evaluator takes in two parameters. Param A is untyped object, and param B is strongly typed. For ease of mind, user might just explicit convert all the values in the expression, even though only param A is required to do so. But `Boolean(A.some_bool)` will succeed but `Boolean(B.some_bool)` will fail.

**Comment by MikeStall** [comment]
To fix:
1. Expand Boolean function to accept bool type. See https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Boolean.cs 
2. Consider Tabular overloads. 
3. Ideally purely a fix in the IR - for `Boolean(x)` when x is a bool, just emit `x`.

**Comment by MikeStall** [comment]
Load balancing....

**Comment by MikeStall** [comment]
Marking Breaking Internal since we will need a corresponding PAClient update to handle this.  (if it was an IR change, we wouldn't...)

Ideally, we could do this as an IR change, but we don't have the contracts in place. 
See #808  -that's just parameters, whereas this is the entire method. 
Table overload - see #874
