### ISSUE TITLE
Shuffle(Table) doesn't work for Lazy Table

### ISSUE THREAD

**Issue by jcoc611-microsoft** [microsoft/Power-Fx#519]
Given a table of a custom lazy type:

```
class LazyTableType : TableType
{
  //...
}
```

Calling `Filter(Table, ...)` works fine but `Shuffle(Table)` complains about argument types. It's possible that other table functions also have this issue, I haven't done an exhaustive search.

Possibly this has to do with [`ShuffleFunction.SupportsParamCoercion` being false](https://github.com/microsoft/Power-Fx/blob/916b15d6a4e2c7915004acf3ef31ec1e58e46c98/src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Shuffle.cs#L22)?

**Comment by MikeStall** [comment]
TableType is sealed now. (recent change).  Is this still an issue?

**Comment by lesaltzm** [comment]
Yup. This was a tiny oversight, turns out. Shuffle calls DType.ToTable even on a table, and we missed a no-op case.
