### ISSUE TITLE
Enable to pass AllowSideEffects flag when creating the RecalcEngineScope

### ISSUE THREAD

**Issue by caiomontei** [microsoft/Power-Fx#523]
When using the EnableSetFunction config, we also need to pass AllowSideEffect = true as parser options for the Eval.

However, it is not possible to pass any parser options when creating a RecalcEngineScope. Causing the LSP to identify the Set function as invalid in the formula bar.

![image](https://user-images.githubusercontent.com/45020185/183123673-50cef16d-8094-4174-bf1b-b66c65cbc59a.png)

**Comment by MikeStall** [comment]
It's easy to create your own scope implementation, but the root issue is that Engine.Suggest() doesn't accept these flags. 
Suggest() calls Check(); and Check has other overloads to accept the flags. 

This probably is just adding the parameter to Suggest().

**Comment by MikeStall** [comment]
Have an overload of Suggest() that accepts a CheckResult.
