### ISSUE TITLE
Connectors -  don't call FromJson(string) since it loses swagger type information

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#530]
Basically, connectors should never call `FormulaValue.FromJson(json)` because that doesn't leverage swagger. 
For example, a string, guid, and date are all the same in json. 

The json+swagger serializer solve this problem. But direct calls to FromJson(json) avoid that. 

One usage is in DecodeResponseAsync(). 
What this means is that if a connector returns a Date (and specifies that in its swagger), we'll call FromJson and deserialize as a string!

**Comment by AlaJaber-Tahaluf** [comment]
I support this issues, I was face this issue and I solved it using this modification:
`
public RecalcEngineScope GetScope(string contextJson)
        {
            var engine = GetEngine();
            var Context = JsonConvert.DeserializeObject<Dictionary<string, object>>(contextJson);
            foreach (var item in Context)
            {
                var value_eval = item.Value?.ToString().Trim('\"');
                var formula_value = EngineContext.GetFormulaValue(engine, value_eval);
                engine.Config.SymbolTable.RemoveVariable(item.Key);
                engine.UpdateVariable(item.Key, formula_value);
            }

            return RecalcEngineScope.FromJson(engine, "{}");
        }
`
where GetFormulaValue function is a custom function that I used to convert a string, object, or list value to a best formula available in RecalcEngine for example when {value_eval} is date e.g. {"20/09/2022"} I convert it to {DateTimeValue("20/09/2022")} and then pass it to `engine.Eval("DateTimeValue(\"20/09/2022\")")` and return value to store it in engine using `engine.UpdateVariable(item.Key, formula_value)`

but still, for this moment I still face some issues with other types, So I wish to solve this issue as soon as
