### ISSUE TITLE
Interpreter purity: injectable providers of non-determinism (DateTime.Now, Random)

### ISSUE THREAD

**Issue by davidnx** [microsoft/Power-Fx#536]
The provided interpreter does not enable deterministic evaluations because some of the built-in functions are non-deterministic and cannot be easily replaced without forking the repo. Some built-in functions that suffer from this:

`Now`, `Today`, `IsToday`, `TimeZoneOffset `, `Rand`, `RandBetween`

Suggestion:
* Expose an interface that consumers of the PowerFx interpreter can replace with arbitrary implementations
* The default implementation of this new interface (or set of interfaces) can remain non-deterministic, and that would make sense perhaps in most use cases

Benefits:
* Better unit-testability (user code could wriet unit tests to validate PowerFx formulae that leverage these non-deterministic functions)
* Globalization support -- would make it possible to evaluate formulae in different timezones

**Comment by MikeStall** [comment]
#503 is in draft and this is exactly one of the goals it will solve.

**Comment by davidnx** [comment]
@MikeStall is my understanding right that #503 would allow one to replace the built-in impls of functions like `Now`, etc. as desired, and this is the mechanism meant to achieve determinism?

While that would unblock here (and regardless is a very useful feature!), IMHO it would require way too much boilerplate for consumers to achieve the present scenario. What I had in mind was something friendlier to modify how the built-in non-deterministic functions work by externalizing the inner logic.

A draft proposa would be something like:

```cs
public interface IPowerFxInterpreterIndeterminismProvider
{
  DateTime Now { get; }
  double NextRandom();
  // ...
}

public class DefaultPowerFxInterpreterIndeterminismProvider : IPowerFxInterpreterIndeterminismProvider
{
  private readonly Random _rnd = new Random();

  public virtual DateTime Now => DaetTime.Now;
  public virtual double NextRandom() => _rnd.Next();
  // ....
}
```

Consumers wanting to get rid of any sources of non-determinism could now have peace of mind knowing this one class gets the job done.

**Comment by MikeStall** [comment]
503 is more than just symbols.  :)

Here's the unit test being added in 503 that demonstrates what you want. The same concept will apply to Rand, etc. 

https://github.com/microsoft/Power-Fx/blob/573abcf3c906e95a50cd9a056cc298d932c4ad43/src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs#L278

It introduces a IServiceProvider to do exactly this: 
https://github.com/microsoft/Power-Fx/blob/573abcf3c906e95a50cd9a056cc298d932c4ad43/src/libraries/Microsoft.PowerFx.Interpreter/Environment/ReadOnlySymbolValues.cs#L18


Hopefully 503 will commit in the next few days, and this issue will follow shortly after.

**Comment by MikeStall** [comment]
@Davidnx - 
Here's an example of Rand() using a service, building upon #503. 

https://github.com/microsoft/Power-Fx/pull/568

**Comment by MikeStall** [comment]
Added these for several key functions now:
#574 - Timezone
#578 - CulutureInfo
#568 - Random
