### ISSUE TITLE
Engine check fails on setProperty()

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#540]
**Original from PR #535.**

Engine check fails on setProperty() when I try to access Comboxbox or Dropdown or Listbox properties. These expect table and record type values.Engine.Check() Fails and throws " **behavior function in a non behavior property error**" .

**Example Engine check() passes**
 `SetProperty(TextInput1.Text, "hi");
 SetProperty(Toggle1.Value, true);` 
**Example Engine check() fails**
`SetProperty(Dropdown1.Selected, {Value:"2"});
SetProperty(ComboBox1.SelectedItems, Table({Value:"1"},{Value:"2"}));          
 SetProperty(ListBox1.SelectedItems, Table({Value:"1"},{Value:"3"}));`

Adding specific testcases where Check() fails.

Would need these Check() to pass

**Comment by MikeStall** [comment]
PR Resolved.
