### ISSUE TITLE
Display Name handling in If() statement, 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#549]
Display Names information doesn't seem to propagate through an If() statement. 

`r1.DisplayName` binds, 

but wrapping it in an If() loses the display name (note both branches are the same type)
`If(true,r1,r1).Display1`
Gets the error:
{Error 14-23: Name isn't valid. 'Display1' isn't recognized.}

If this is actually by design, we should give a better error message. 

Consider this test 

        [Fact]
        public void DisplayName2()
        {
            var r1 = RecordType.Empty()
                        .Add(new NamedFormulaType("F1", FormulaType.Number, "Display1"))
                        .Add(new NamedFormulaType("F0", FormulaType.Number, "Display0")); // Common

            var parameters = RecordType.Empty()
                .Add("r1", r1);

            var engine = new Engine(new PowerFxConfig());

            var result = engine.Check("r1.Display1", parameters);
            Assert.True(result.IsSuccess); // Succeeds

            // If takes the subset, common fields from each. 
            result = engine.Check("If(true,r1,r1).Display1", parameters); // !!!   Fails!!!!
            Assert.True(result.IsSuccess);
        }

Related issues:
- What happens when there are different types like `If(test,r1,r2).Display` . Can we trick Display to bind to different fields on r1,r2? 
- At the SDK level, should RecordValue.GetField() handle display names?

**Comment by lesaltzm** [comment]
Look at DType.SupertypeAggregateCore which is what If uses to combine branch types. It unions the DataSource metadata, but not DisplayNameProviders.
