### ISSUE TITLE
Intellisense shouldn't suggest Table.Columns if that's deprecated

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#561]
We're deprecating `Table.Columns`  - where Column returns a single column from table. 
PowerApps supports; but Intepreter does not.   

Intellisense still suggests this; it shouldn't if this is deprecated. 
![image](https://user-images.githubusercontent.com/1538900/185002752-6802287d-822c-4039-bc8e-2c44b2577846.png)

Do we need a feature flag on this?

**Comment by lesaltzm** [comment]
No on the flag need, intellisense behavior has no back-compat impact, and tbh, it'd be good to not suggest this in canvas either, it's very rare that users intend to use single column table syntax, and we've seen incidents in the past from this confusion.

**Comment by lesaltzm** [comment]
IntellisenseHelper.AddSuggestionsForNamesInType looks like where this change would live.
