### ISSUE TITLE
Add support to selectively remove functions from the default symbol table

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#588]
I'm looking for a way to disable (or remove entirely) some of the built-in functions added in the config.
I've looked at the new symbol table changes, but there are still some gaps:
1. `ReadOnlySymbolTable` is namely, read only. So I can't selectively remove functions from the default `Engine.SupportedFunctions` table.
2. I still want to use many Power FX built in functions, but I can't selectively add them to a `SymbolTable` because the built in functions are internal (and the `BuiltinFunctionsCore` is also internal)

An offline recommendation from Mike is to potentially provide a `ReadOnlySymbolTable.GetMutableCopy()` that returns a `SymbolTable ` that we can mutate.

**Comment by MikeStall** [comment]
Fixed
