### ISSUE TITLE
Help() have redundant function names 

### ISSUE THREAD

**Issue by fadyanwar** [microsoft/Power-Fx#60]
Several function names are repeated twice on the help message output of Help(), such as Max, Sum and Average

**Comment by MikeStall** [comment]
This is referring to https://github.com/microsoft/power-fx-host-samples/tree/main/Samples/ConsoleREPL  ?
This is probably showing all the overloads - ie both the table and scalar versions. 
For Help(), we could consider grouping by overload.

**Comment by fadyanwar** [comment]
Yes, I've found it via the REPL console sample, but if I'm not mistaken the Help() is implemented in the core PowerFx library.

**Comment by MikeStall** [comment]
Help()  is a helper function in the Console repl sample: 
https://github.com/microsoft/power-fx-host-samples/blob/417a3100b96420167004e259c06ed8c4d81d7420/Samples/ConsoleREPL/ConsoleREPL.cs#L182

The problem is engine.GetAllFunctionNames() is including overloads.

**Comment by fadyanwar** [comment]
Interesting, I was under the impression that all functions are self contained in the Nugets.

**Comment by MikeStall** [comment]
The built-in ones are in the core nuget. But hosts can extend with additional helpers.
