### ISSUE TITLE
Multi Dymentional Tables

### ISSUE THREAD

**Issue by sirinath** [microsoft/Power-Fx#62]
To make the language more powerful and useful tables should become multi dimensional.

**Comment by lesaltzm** [comment]
@sirinath , can you clarify this a bit? You can nest tables in PowerFx already, 
`[ [1, 2, 3], [4,5,6], [7,8,9] ]` is valid in PowerFx. The distinction here is that everything within a table is associated with a Key, so the inner table here is under the 'Value' key by default.

**Comment by lesaltzm** [comment]
Reopen if there's something missing here, but we do support multidimensional tables as defined above.
