### ISSUE TITLE
Error 'The first argument of 'Count' should be a one-column table' on lazy record type with one column

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#629]
Here is the test that fails:

        private class LazyRecordType : RecordType
        {
            public override IEnumerable<string> FieldNames => GetFieldNames();

            public LazyRecordType()
                : base()
            {
            }

            public override bool TryGetFieldType(string name, out FormulaType type)
            {
                switch (name)
                {
                    case "SomeNumber":
                        type = FormulaType.Number;
                        return true;
                    default:
                        type = FormulaType.Blank;
                        return false;
                }
            }

            private IEnumerable<string> GetFieldNames()
            {
                yield return "SomeNumber";
            }

            public override bool Equals(object other)
            {
                return other is LazyRecordType; // All the same 
            }

            public override int GetHashCode()
            {
                return 1;
            }
        }

        [Fact]
        public void CountFunctionWithLazyRecordType()
        {
            var engine = new Engine(new PowerFxConfig(CultureInfo.InvariantCulture));

            var r1 = RecordType.Empty()
                .Add(new NamedFormulaType("array", new LazyRecordType().ToTable(), "array"));

            var result = _engine.Check("Count(array)", r1);
            Assert.True(result.IsSuccess);
        }

**Comment by LucGenetier** [comment]
Already fixed
