### ISSUE TITLE
Better Support for n-D Array Formulas

### ISSUE THREAD

**Issue by sirinath** [microsoft/Power-Fx#63]
Excel has upto 3D array formulas. Power Fx also should have the notion of an n-D array which can contain a mix of other variables, arrays or array slices and tables or table slices.

**Comment by lesaltzm** [comment]
Power Fx supports nested tables as is today, although our type system requires that they be of a homogenous type. If you're looking for support of heterogeneously typed nested tables, UntypedObject and ParseJson will be the closest we can get in Power Fx.
