### ISSUE TITLE
Need public replacement for Config.FunctionInfos

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#677]
The ConsoleREPL has this line:
`                var funcNames = engine.Config.FunctionInfos.Select(x => x.Name).Distinct();`

At compile time, this message appears:
`warning CS0618: 'PowerFxConfig.FunctionInfos' is obsolete: 'Migrate to SymbolTables'`

From these lines in PowerFxConfig.cs:
```
        /// <summary>
        /// Information about available functions.
        /// </summary>
        [Obsolete("Migrate to SymbolTables")]
        public IEnumerable<FunctionInfo> FunctionInfos => 
            new Engine(this).SupportedFunctions.Functions
            .Concat(SymbolTable.Functions)
            .Select(f => new FunctionInfo(f));
```
I'm happy to change the ConsoleREPL, but I'm not sure what I can change it to.  Engine.SupportedFunctions doesn't appear to have any public stuff to work with.

Please advise if there is an existing public way to do this, or if we need to add a non-obsolete public mechanism.  Getting the list of supported functions is very helpful for hosts.

**Comment by MikeStall** [comment]
Engine.SupportedFunctions  is the right way to go. 
ReadOnlySymbolTable needs a public accessor to provide this.

**Comment by MikeStall** [comment]
moving back to 1.0 per discussion
