### ISSUE TITLE
additional data types for custom functions needed

### ISSUE THREAD

**Issue by timnudecision** [microsoft/Power-Fx#69]
only numerical valued custom functions with numrerical arguments are supported.  adding strings and bools would be great for starters.

many thanks for the important work being done here!

**Comment by rajyraman** [comment]
I also hit this issue today. Did not realise that only NumberValue is supported (https://github.com/microsoft/Power-Fx/blob/47f0dfc2b13dcbdd8a2310289c902e19f9752314/src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs#L132). It would be good to get a timeline for support of other types.

**Comment by rajyraman** [comment]
@timnudecision - It is possible to use other data types as well. Please see _Creating new Functions in Power Fx_  section in the notebook https://github.com/rajyraman/Power-Fx-.NET-Interactive/blob/main/notebooks/PowerFx.ipynb

**Comment by tjohnston-fcg** [comment]
@rajyraman that works, thanks.

**Comment by MikeStall** [comment]
We also need support for async functions (returning task), and likely leveraging the new TypeMarshaller support.
