### ISSUE TITLE
Disable row-scope disambiguation syntax for C# hosts

### ISSUE THREAD

**Issue by lesaltzm** [microsoft/Power-Fx#698]
`table[@Field]` instead of As is currently still supported in the C# host. We should remove this support before shipping V1. 

Now, user would need to use
`Filter(A, ThisRecord.Value = 2)` or `Filter(A As Foo, Foo.Value = 2)`
instead of
`Filter(A, A[@Value] = 2)`

**Comment by lesaltzm** [comment]
![image](https://user-images.githubusercontent.com/69215460/192655374-e0b93223-60bf-46fc-ad48-25a34f6639bc.png)

**Comment by lesaltzm** [comment]
Luckily this is easy to clean up. returning early from Binder.cs::IsRowScopeAlias() based on a flag would disable this.

**Comment by MikeStall** [comment]
Note that _just_ returning false from IsRowScopeAlias will cause us to hit other cases and still attempt to bind the expressions. So we should at just give an error if IsRowScopeAlias  is true. 

Or better yet - IsRowScopeAlias is at the binder - can we disable at the parser level?

Should also confirm that **intellisense _doesn't_ suggest it.** 

![image](https://user-images.githubusercontent.com/1538900/194601161-8c97d2eb-f36f-4d13-acf7-46e577ef592a.png)

**Comment by jas-valgotar** [comment]
Do we also disable it in the case of unqualified field name?
e.g. Filter([1,2,3],ThisRecord[@Value]=2)
