### ISSUE TITLE
String operations should honor PowerFxConfig's CultureInfo 

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#711]
I'd expect the all operations that involves locale/culture should honor PowerFxConfig culture setting, but looks like we'll using the CurrentCulture of the host instead.

Example
```c#
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("tr-TR");

var config = new PowerFxConfig(System.Globalization.CultureInfo.InvariantCulture);
var engine = new RecalcEngine(config);
...

```
Then we get the Turkish culture instead of the invariant version
`Upper("indigo")` --> `İNDİGO`

Same problem applies to `Lower`, `Proper`

Same problem would likely occur in string comparison operations as well, but I couldn't find such functions.

**Comment by susosuso** [comment]
Another related one is temporal data.

if I set host culture
`System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("tr-TR");`
then
```
> Text(DateTimeValue("10/11/2014 1:50:24.765 PM", "tr-TR"))
10.11.2014 13:50
```

If I set host back to default (en-US), then
```
> Text(DateTimeValue("10/11/2014 1:50:24.765 PM", "tr-TR"))
10/11/2014 13:50
```

expected?

**Comment by susosuso** [comment]
I did a quick check with the latest daily builds, looks like Proper() isn't updated

`Proper("indIgo")` --> `Indıgo`
`Proper("INDIGO")` --> `ındıgo`

https://github.com/microsoft/Power-Fx/blob/a8e4eaefd6349522c06a2e9a5c7a26848775f458/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs#L293

Probably should be 
```csharp
return new StringValue(irContext, runner.CultureInfo.TextInfo.ToTitleCase(runner.CultureInfo.TextInfo.ToLower(args[0].Value)));
```


(not sure if ToLower() is really necessary here...)

**Comment by anderson-joyle** [comment]
Hi @susosuso. I've tried a few scenarios from my end and couldn't simulate your problem.
There is a test case checking if Proper is working as intended:
https://github.com/microsoft/Power-Fx/blob/a8e4eaefd6349522c06a2e9a5c7a26848775f458/src/tests/Microsoft.PowerFx.Interpreter.Tests/ConfigTests.cs#L347

Can you please elaborate what your scenario is?
