### ISSUE TITLE
Add support for UTCNow, UTCToday, IsUTCToday 

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#718]
`Now()`, `Today()`, `IsToday()` are taking the time zone of the "current user", which is not ideal for server-side product to consume.

Can we support `UTCNow`, `UTCToday`, `IsUTCToday`, like how Microsoft Dataverse has it, as mentioned in the [documentation](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-now-today-istoday#description)?

**Comment by MikeStall** [comment]
Note to implementors - this should use the same time service / dependency injection that we use for Now(), Today(), etc.

**Comment by MikeStall** [comment]
As a mitigation, the engine can set the current timezone to UTC and call Now() 

https://github.com/microsoft/Power-Fx/blob/631173631d3b4ab9dd06d6fe2d3a2a2451c100cf/src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs#L839

**Comment by susosuso** [comment]
Thanks Mike for the suggestion. I played around with it. `Now()` works as expected after setting the time zone, but it didn't work for other scenarios:

| |Test cases | Value |  |
| - | --- | ------ | --- | 
|  | C#'s `DateTime.UtcNow` | `2022-11-18T00:45:19.9013114Z`| |
|  | C#'s `DateTime.Now` | `2022-11-17T16:45:19.9013114-08:00`| |
| 1 | `myDateTime` <br>(which is `FormulaValue.New(DateTime.Now)`) | `2022-11-17T16:45:19.9013114-08:00`|  |
| 2 | `myDateTime`, <br>with `SetTimeZone(TimeZoneInfo.Utc)` | `2022-11-17T16:45:19.9013114-08:00`| How can I make it to be in UTC? |
| 3 | `Now()` | `2022-11-17T16:45:19.9013114-08:00` |
| 4 | `Now()`, <br>with `SetTimeZone(TimeZoneInfo.Utc)` | `2022-11-18T00:45:19.9013114Z` |
| 5 | `DateTime(2022,11,17,1,0,0)` | `2022-11-17T01:00:00.0000000` | 
| 6 | `DateTime(2022,11,17,1,0,0)`, <br>with `SetTimeZone(TimeZoneInfo.Utc)` | `2022-11-17T01:00:00.0000000` | How can I make it to be in UTC? |
| 7 | `IsToday(DateTime(2022,11,17,1,0,0))` | `True` |
| 8 | `IsToday(DateTime(2022,11,17,1,0,0))`, <br>with `SetTimeZone(TimeZoneInfo.Utc)` | `True` | This seems wrong to me. <br>Looks like `IsToday` is just <br>checking the local time [here](https://github.com/microsoft/Power-Fx/blob/81b3c7c5917a940a20f9730317b41a99895ca836/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs#L40).<br> Likewise for `Today()` |

In general, I'd like all date times to be treated as UTC unless specified explicitly. Out of all the test cases above, 2, 6 and 8 seems incorrect to me. Is there some other config I should tune to make them in UTC?

I'm also curious to learn the why we're blocking `DateTimeValue()` be created when `System.DateTimeKind` is UTC. Ideally, we'd like to be able to do something like `Formula.New(DateTime.UtcNow)`. Not absolutely necessary though.

In case you're curious about the test code --
```csharp
// Setup
var engine = new RecalcEngine(
    new PowerFxConfig(System.Globalization.CultureInfo.InvariantCulture));
var utcNow = DateTime.UtcNow;
var localNow = utcNow.ToLocalTime();

Console.WriteLine($"UTC now: {utcNow.ToString("o")}");
Console.WriteLine($"local now: {localNow.ToString("o")}");

var symbolTable = new SymbolTable();
symbolTable.AddVariable("myDateTime", FormulaType.DateTime);

var parse = engine.Parse("myDateTime");
var evaluator = engine.Check(parse, null, symbolTable).GetEvaluator();

// Test local now as variable
var symbolValues = new SymbolValues().Add("myDateTime", FormulaValue.New(localNow)); // DateTimeKind.Utc is not allowed here...
var result = await evaluator.EvalAsync(default, symbolValues).ConfigureAwait(false);
Console.WriteLine($"PowerFX eval 'myDateTime': {((DateTime)result.ToObject()).ToString("o")}");

// Test again, but with SetTimeZone()
symbolValues.SetTimeZone(TimeZoneInfo.Utc);
result = await evaluator.EvalAsync(default, symbolValues).ConfigureAwait(false);
Console.WriteLine($"PowerFX eval 'myDateTime', w/ UTC timezone: {((DateTime)result.ToObject()).ToString("o")}");

// Test Now()
parse = engine.Parse("Now()");
evaluator = engine.Check(parse, null, symbolTable).GetEvaluator();
result = await evaluator.EvalAsync(default, new SymbolValues()).ConfigureAwait(false);
Console.WriteLine($"Now(): {((DateTime)result.ToObject()).ToString("o")}");

// Test Now() again, but with SetTimeZone()
result = await evaluator.EvalAsync(default, symbolValues).ConfigureAwait(false);
Console.WriteLine($"Now(), w/ UTC timezone: {((DateTime)result.ToObject()).ToString("o")}");

// Test DateTime 'literal'
parse = engine.Parse("DateTime(2022,11,17,1,0,0)");
evaluator = engine.Check(parse, options: null, null).GetEvaluator();
result = await evaluator.EvalAsync(default, new SymbolValues()).ConfigureAwait(false);
Console.WriteLine($"DateTime(2022,11,17,1,0,0): {((DateTime)result.ToObject()).ToString("o")}");

// Test DateTime 'literal', but with SetTimeZone()
result = await evaluator.EvalAsync(default, symbolValues).ConfigureAwait(false);
Console.WriteLine($"DateTime(2022,11,17,1,0,0)), w/ UTC timezone: {((DateTime)result.ToObject()).ToString("o")}");

// Test IsToday()
parse = engine.Parse("IsToday(DateTime(2022,11,17,1,0,0))");
evaluator = engine.Check(parse, options: null, null).GetEvaluator();
result = await evaluator.EvalAsync(default, new SymbolValues()).ConfigureAwait(false);
Console.WriteLine($"IsToday(DateTime(2022,11,17,1,0,0)): {result.ToObject()}");

// Test IsToday(), but with SetTimeZone()
result = await evaluator.EvalAsync(default, symbolValues).ConfigureAwait(false);
Console.WriteLine($"IsToday(DateTime(2022,11,17,1,0,0)), w/ UTC timezone: {result.ToObject()}");

```

**Comment by BetimBeja** [comment]
The time behavior of PowerFX is documented [here](https://learn.microsoft.com/en-us/power-platform/power-fx/data-types?WT.mc_id=DX-MVP-5004767#time-zones). Please note the following:

> For **User local** date/times, canvas apps use the time zone of the browser or device, but model-driven apps use the user's setting in Dataverse. These settings typically match, but results will differ if these settings differ.

Also note that the C# DateTime.Now is using the TimeZone information of the computer it is currently executing, which is different from the previous statement from Microsoft Docs.

I have written a [blog post](https://xrm.al/blog/datetime-zone) some time ago about handling different TimeZones in Dataverse, if that helps. Hint, to break free from the computer TimeZone information you need to use the [DateTime.Kind = Unspecified](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-7.0&WT.mc_id=DX-MVP-5004767#system-datetimekind-unspecified)

**Comment by MikeStall** [comment]
Here's what I think we should do at the SDK level:

**[1] Avoid any direct usage of DateTime.Today / DateTime.Now / DateTime.UtcNow within the code** 
Those APIs directly use machine specific settings, and instead we need to be using the engine’s settings. 
This may fix row 8

**[2] Allow FormulaValue.New(datetime) to accept UTC or local time.** 
Remove this restriction: https://github.com/microsoft/Power-Fx/blob/e38b709dde50f1ed927315f25b9e6b8e1d1688db/src/libraries/Microsoft.PowerFx.Core/Public/Values/FormulaValueNew.cs#L91

This restriction is forcing hosts to call DateTime.ToLocalTime() themselves, which is dangerous since it isn't consistent with engine settings (violates 1 above). 

Instead, normalize timezone at point of usage within the engine. The engine will have the settings 
This will fix row 1 and 2.

**[3] Ensure Fx Functions all honor Engine.SetTimeZone()** 
Now() does, but DateTime() does not- see row 6 above. 

When in Engine.TimeZoneSettings are in UTC, taking this Fx expression: 
`DateTime(2022,11,17,1,0,0)`

And extracting it’s C# DateTime, should produce this:
`new DateTime(2022,11,17,1,0,0, DateTimeKind.Utc).ToString("o")
"2022-11-17T01:00:00.0000000Z"`
