### ISSUE TITLE
Can I make a custom filter function using ReflectionFunction?

### ISSUE THREAD

**Issue by nathansoz** [microsoft/Power-Fx#733]
I'm not sure if this is a documentation gap or a functionality gap, but it isn't clear to me how I can create a generic filter function using ReflectionFunction. For example, the function distinct does not exist in the runtime yet (#732) and I was thinking I would replicate it. Ideally, I could pass it a table along with a formula that gets evaluated to determine what to operate over.

**Comment by MikeStall** [comment]
This depends on #643

**Comment by anderson-joyle** [comment]
https://github.com/microsoft/Power-Fx/issues/643 is closed.
