### ISSUE TITLE
Add the ability to restrict certain data types from being used

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#749]
Certain data types are not applicable to our scenarios -- for examples, `Color`. If possible, we'd like to be able to block off the ability to use those types in Power FX expressions. Perhaps exposing the settings in PowerFxConfig?

**Comment by anderson-joyle** [comment]
Just for curiosity, is there a scenario where you expect a certain data type but ends up getting an unwanted one (like `Color`)?

**Comment by MikeStall** [comment]
Some options:
1. You can walk the tree (after check) and reject "bad" types, using a visitor on 
2. you can restrict incoming Functions and Enums to block generating types. 

To be airtight, this would have to be done after the "deferred types" are substituted - else a deferred type make introduce one of the banned types. 

Fx can consider something like an overload on Engine that's called by Check() to ensure this walker gets invoked. That would cover both check and intellisense scenarios.

**Comment by MikeStall** [comment]
Fixed with #993
