### ISSUE TITLE
Minor changes from PR #746

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#751]
Two minor changes still remain from PR #746:

- [Pass **locale** argument as a named argument.](https://github.com/microsoft/Power-Fx/pull/746#discussion_r992894369): Resolved with #764 
- [Translate ERROR text to given locale.](https://github.com/microsoft/Power-Fx/pull/746#discussion_r992773836)

**Comment by MikeStall** [comment]
Note that we now lazily localize error messages, so passing culture to errors is no longer necessary.  See #1040
