### ISSUE TITLE
Overload of Error that just takes string 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#765]
This should work:
`Error("value too high")`

These are supported today, but they're too verbose:
`Error(Table({Kind:ErrorKind.Div0, Message :"Div0"}))`
`Error({Kind:ErrorKind.Validation, Message :"Value too high"})`

Note the overload should also play with the type system so this should work:
`IfError(Error(Table({Kind:ErrorKind.Div0, Message :"MyError"})), FirstError.Message)` // MyError

Also determine the default ErrorKind. For Business Rules, most failures will be Validation.

**Comment by anderson-joyle** [comment]
Are we also implementing other variations such as:
`Error(["Error message 1","Error message 2","Error message 3"])`
`Error(ErrorKind.Div0)` // Default error message depending on error kind

UPDATE:
After speaking to internal team, 1st variation wont be implemented (at least for now). 2nd variation maybe in the future.
