### ISSUE TITLE
Eval Record in EngineRecalc (Reorder Attributes)

### ISSUE THREAD

**Issue by AlaJaber-Tahaluf** [microsoft/Power-Fx#772]
when try using ConsoleREPL to create record in engine, its re-order for the attributes in record as you can see in below image:
![image](https://user-images.githubusercontent.com/111876963/196382208-63dd5056-d7a2-4e29-83a7-7df89651ffde.png)
![description_object](https://user-images.githubusercontent.com/111876963/196382236-e4b4462a-4f72-4959-8cc3-d7b0d77dbbc4.png)
![image](https://user-images.githubusercontent.com/111876963/196382325-43466bd0-4fc8-48fc-a6a1-465cbdc73753.png)

How I can solve this issue

**Comment by AlaJaber-Tahaluf** [comment]
I solved it using this code
![image](https://user-images.githubusercontent.com/111876963/196385164-75e87a5f-85ae-40f6-a70c-9da9d969eb9b.png)

**Comment by MikeStall** [comment]
Records fields are not ordered - this is by-design per the language semantics.  Some of the tools will print them in alphabetical order. 

This is similar for C# fields and C# dictionaries. 

Can you tell me more about your scenario?

**Comment by AlaJaber-Tahaluf** [comment]
I am trying to create a record using JSON format and after some operations with this record I want to print it
But as you can see in the image above, the columns of record are not identical to the order of properties in JSON when entered

**Comment by lesaltzm** [comment]
JSON objects are also unordered ([see json spec](https://www.rfc-editor.org/rfc/rfc8259.html)). 

>  An object is an unordered collection of zero or more name/value
   pairs, where a name is a string and a value is a string, number,
   boolean, null, object, or array.

From a JSON perspective, that output, and the corresponding input object would be considered equivalent.
