### ISSUE TITLE
Add Clear and ClearCollect functions

### ISSUE THREAD

**Issue by caiomontei** [microsoft/Power-Fx#829]
We are missing Clear and ClearCollect functions that exist on Power Apps.

[Collect, Clear, and ClearCollect functions in Power Apps](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-clear-collect-clearcollect)

**Comment by MikeStall** [comment]
Note that certain data sources may restrict these - so failure is a common result. For example, dataverse blocks these calls so that makers don't accidentally delete an entire table.
