### ISSUE TITLE
Error NETSDK1187 when compiling with .Net 7

### ISSUE THREAD

**Issue by BrunoGuardia** [microsoft/Power-Fx#838]
The resource file has the wrong casing, which causes a warning in .NET 7.

[error]/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): Error NETSDK1187: Package Microsoft.PowerFx.Core 0.2.3-preview.20221111-328978 has a resource with the locale 'ko-kr'. This locale has been normalized to the standard format 'ko-KR' to prevent casing issues in the build. Consider notifying the package author about this casing issue.

**Comment by MikeStall** [comment]
It's this file: 
https://github.com/microsoft/Power-Fx/blob/main/src/strings/PowerFxResources.ko-kr.resx

**Comment by BrunoGuardia** [comment]
Seems there are two more

https://github.com/microsoft/Power-Fx/blob/main/src/strings/PowerFxResources.zh-tw.resx
https://github.com/microsoft/Power-Fx/blob/main/src/strings/PowerFxResources.zh-cn.resx

**Comment by MikeStall** [comment]
Thanks for filing and fixing, @brunoGuardia!
