### ISSUE TITLE
Using SymbolValues with ExpressionEvaluator: Slot is not valid on Symbol Table

### ISSUE THREAD

**Issue by babrekel** [microsoft/Power-Fx#860]
After updating to a more recent version, starting to get this exception. It might be related to this PR:   #817

`InvalidOperationException: Slot 'x:FromRecord_25763907' is not valid on Symbol Table (FromRecord,Globals,BuiltinFunctions (140),DefaultConfig)_1656543` 

A minimal repro: 

```
var values = new SymbolValues();
values.Add("x", FormulaValue.New(5));

var engine = new RecalcEngine();
var checkResult = engine.Check("x", RecordType.Empty().Add("x", FormulaType.Number));

var result = await checkResult.GetEvaluator().EvalAsync(CancellationToken.None, values);
```

Note that it doesn't reproduce when using Engine.EvalAsync directly.

**Comment by MikeStall** [comment]
This is by-design. the gist is that the symbols and check and eval need to correlate. 
See here for an example of how to do it: 
https://github.com/microsoft/Power-Fx/blob/94525664887f1eda23e0f6e67a3cb276421d9777/src/tests/Microsoft.PowerFx.Interpreter.Tests/SymbolValueTests.cs#L207

This becomes a bigger as the symbols get more complex (dataverse, connections, globals, etc), and we need to avoid elaborate lookups at runtime.

**Comment by MikeStall** [comment]
#900 adds a runtime check to catch this, and a new test.

**Comment by MikeStall** [comment]
#951 adds even stronger error message.
