### ISSUE TITLE
DateTimeValue(UntypedObject) should allow higher precision of decimal fraction than 3

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#895]
When parsing an UntypedObject string to DateTime object, I noticed it has very strict precision for second decimal fractions.

```DateTimeValue(ParseJSON("""2011-01-30T08:00:00.000Z"""))``` works, but

```DateTimeValue(ParseJSON("""2011-01-30T08:00:00.0005Z"""))``` will fail.

My guess is that this was intended to keep compatibility with MySql ? but my two cents is that Power Fx should be more flexible, especially when feeding it with plain string work just fine:
`DateTimeValue("2011-01-30T08:00:00.0005Z")` works

https://github.com/microsoft/Power-Fx/blob/2e9130f2352b3a04a910a4ca86c8e8cb44c4e2c3/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs#L22

Not super important, as we can drop the fractions if needed, despite losing some precision.

**Comment by susosuso** [comment]
similarly, for TimeValue:

`TimeValue(ParseJSON("""11:12:00.000"""))` works, but
`TimeValue(ParseJSON("""11:12:00"""))` fails.

https://github.com/microsoft/Power-Fx/blob/2e9130f2352b3a04a910a4ca86c8e8cb44c4e2c3/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryUntypedObject.cs#L184

**Comment by MikeStall** [comment]
From Carlos: "We should allow that. Since we decided that we will support up to 7 fractional digits in date/time, that should work as well."

We should update the .txt tests as well to reflect this.
