### ISSUE TITLE
Unable to debug using sourcelink

### ISSUE THREAD

**Issue by rajyraman** [microsoft/Power-Fx#90]
When I try to use LanguageServer, I am getting -32602 (InvalidParams) error. So, I would like to Debug using Source Link. When I step through to Power Fx code, I get the error below.

![image](https://user-images.githubusercontent.com/5035266/146434868-f1017149-4720-4f38-b095-2d70fe2ccae5.png)

Please update the Source Link information for the assemblies published on Nuget. If I ignore the warning and use the LanguageServer file on my local machine, the debug is all messed up and I am unable to step through properly.

**Comment by lbargaoanu** [comment]
I have a similar problem. SourceLink doesn't seem to point to the public sources.

**Comment by lesaltzm** [comment]
Thanks for pointing this out. The public Nuget packages were published from our private staging repo, we'll publish a new one from this repo and get that fixed up soon.

**Comment by lesaltzm** [comment]
0.2.2-preview published to nuget.org. Should have up-to-date source link information.  (https://www.nuget.org/packages/Microsoft.PowerFx.Core/0.2.2-preview)
