### ISSUE TITLE
Enable Globalization checks via .Net Analyzers & character encoding

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/Power-Fx#909]
Compliance task 16183216 - Validate Correct Text and Data Encoding
Refer to https://microsoft.sharepoint.com/:w:/t/CEIntl/WR/EZIX72BUXShDuoqH8CLmYo4BY9ebrrOF6hHnjRZe-PjebA?e=loXJnU

**Comment by LucGenetier** [comment]
.Net analyzers -> https://github.com/microsoft/Power-Fx/pull/913

**Comment by LucGenetier** [comment]
Need some tests to be run with the following locales and corresponding characters: Arabic, Chinese (simplified + traditional), German, Hebrew, Hindi, Japanese, Korean, Thai, Turkish, Portuguese, Russian, Italian, French, Greek, Czech, Danish, Finnish
Tests with dates, times, decimal numbers
Enable .Net analyzer globalization rules - https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/globalization-warnings 
Out of scope: non Gregorian calendar (Arabic - Saudi Arabia)

**Comment by MikeStall** [comment]
Fixed with #1143
