### ISSUE TITLE
Texl errors are not localized

### ISSUE THREAD

**Issue by Robulane** [microsoft/Power-Fx#918]
Constructor of BaseError has the following line:

(var shortMessage, var longMessage) = ErrorUtils.GetLocalizedErrorContent(errKey, null, out var errorResource);

Null being passed is the CultureInfo. As we always pass null, errors are not localized. Here is the unit test that demonstrates the issue. (to copy paste in LanguageServerTests file):

        [Fact]
        public void ErrorIsLocalized()
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fr-fr");
            var config = new PowerFxConfig();
            config.AddFunction(new BehaviorFunction());
            var engine = new Engine(config);

            _sendToClientData = new List<string>();
            _scopeFactory = new TestPowerFxScopeFactory(
                (string documentUri) => engine.CreateEditorScope(new ParserOptions() { Culture = CultureInfo.InvariantCulture }, GetFromUri(documentUri)),
                GetParserOptions(false));
            _testServer = new TestLanguageServer(_sendToClientData.Add, _scopeFactory);

            _testServer.OnDataReceived(
                JsonSerializer.Serialize(new
                {
                    jsonrpc = "2.0",
                    method = "textDocument/didOpen",
                    @params = new DidOpenTextDocumentParams()
                    {
                        TextDocument = new TextDocumentItem()
                        {
                            Uri = "powerfx://app",
                            LanguageId = "powerfx",
                            Version = 1,
                            Text = "Bla."
                        }
                    }
                }));

            CheckBehaviorError(_sendToClientData[0], false, out var diags);

            Assert.DoesNotContain("Unexpected characters.", diags.First().Message); // the value should be localized. Resx files have this localized.
        }

**Comment by anderson-joyle** [comment]
Thanks for taking the time to share this.
Error messages are translated directly in the ParseResult object, taking the following order of priority:

1. ParseOption locale
2. PowerFxConfig locale
3. Current machine locale

In your example, although `Thread.CurrentThread.CurrentCulture` is set to **fr-FR**, the ParseOptions is created with an `CultureInfo.InvariantCulture` locale.

_engine.CreateEditorScope(new ParserOptions() { **Culture = CultureInfo.InvariantCulture** }, GetFromUri(documentUri)), GetParserOptions(false));_

This is going to affect the error messages.
The following snippet is a version of your test case:

```
[Fact]
        public void ErrorIsLocalized()
        {
            var engine = new Engine(new PowerFxConfig());

            // ParseOptions locale
            var locale = CultureInfo.CreateSpecificCulture("fr-FR");

            engine.Config.AddFunction(new BehaviorFunction());

            _sendToClientData = new List<string>();
            _scopeFactory = new TestPowerFxScopeFactory(
                (string documentUri) => engine.CreateEditorScope(new ParserOptions() { Culture = locale }, GetFromUri(documentUri)),
                GetParserOptions(false));
            _testServer = new TestLanguageServer(_sendToClientData.Add, _scopeFactory);

            _testServer.OnDataReceived(
                JsonSerializer.Serialize(new
                {
                    jsonrpc = "2.0",
                    method = "textDocument/didOpen",
                    @params = new DidOpenTextDocumentParams()
                    {
                        TextDocument = new TextDocumentItem()
                        {
                            Uri = "powerfx://app",
                            LanguageId = "powerfx",
                            Version = 1,
                            Text = "Bla."
                        }
                    }
                }));

            CheckBehaviorError(_sendToClientData[0], false, out var diags);

            // Checking if contains text in the correct locale
            Assert.Contains("Caractères inattendus.", diags.First().Message); // the value should be localized. Resx files have this localized.
        }
```

As a side note, there is [this open discussion](https://github.com/microsoft/Power-Fx/discussions/872) that contains a few more details about localization. This documentation is still a work in progress.

**Comment by Robulane** [comment]
I think this is incorrect. 

CultureInfo in ParserOptions is used to parse the formula. E.g. in French we use ";" as a separator and in English we use "," as a separator.

What we want is to get localized error messages for Invariant formula.

**Comment by Robulane** [comment]
The order mentioned in the reply contradicts the order documented here: https://github.com/microsoft/Power-Fx/discussions/872
