### ISSUE TITLE
With+Collect crashes

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#920]
This crashes in REpl:

```
> Set(x, { v :1 , t: [1,2,3]})
x: {t:[1, 2, 3], v:1}

> x.t
[1, 2, 3]

> With({ y : x.t}, Collect(y, { Value: 99}))
```

Expected after the collect is:
```
> x.t 
[1, 2, 3, 99]
```

**Comment by MikeStall** [comment]
It's related to #915. 
The runtime type from the Collect() is a record, but the compile time type is the whole table. 
The assert is catching that mismatch.

**Comment by anderson-joyle** [comment]
Both #920 and #925 will be fixed in a single PR.
