### ISSUE TITLE
Text(123.466, "[$-en-US]$#0.0M")

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#932]
PowerApps supports this:
`Text(123.466, "[$-en-US]$#0.0M") // $123.5M`

The 'M' is treated as an unrecognized character and emitted directly to output. 

PowerApps changes this for Excel compact. 
#890  is the corresponding change in the interpreter.

**Comment by MikeStall** [comment]
Not sure what the right fix is here (is this by-design, is there a bug , etc). Determine correct behavior and handle accordingly.

**Comment by gregli-msft** [comment]
This appears to have been fixed.  It should produce an error, same as Canvas and Excel.

```
> Text(123.466, "[$-en-US]$#0.0M")
Error: InvalidArgument - Incorrect format specifier for 'Text'.
```
