### ISSUE TITLE
Avoid Task.WhenAll

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#954]
We should avoid using Task.WhenAll  within the interpreter. 
Task.WhenAll runs in parallel, and is used by ForAll and other table functions. 

Note that we currently expect parallel semantics in these cases:
https://github.com/microsoft/Power-Fx/blob/2c3ee1bae5f48e7196076877e2fc584825b05b47/src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterExpressionTestCases/ParallelAsync.txt#L27

Why?

1. **Avoid multi-threaded bugs**: The interpreter evaluation is **single threaded**, although multiple evals can be run concurrently; and many of the objects flowing through are also single threaded.  We need to be sure that these don't cause single-threaded code to be run in multi-threaded execution.   Collect() and mutation functions are the big concern here. 
If we reason the semantics do allow parallel execution, we need some significant stress testing. 

2. **Semantics w/ behavior functions**: This can also be significant for side-effecting operations like ForAll(...Collect ...).  We need to clarify language semantics about whether ForAll on behavior is serialized. 

3. **Protection against resource abuse**:  In server scenarios - we want to limit the impact of a single Eval(). Allowing it to run multi-threaded means that one expression could expand to take all the server resources. 
Whereas keeping it single threaded means we can track memory usage on that thread (via .Net's GC class) and that a long running expression will safely timeout rather than just consume all the server threads.

**Comment by nguhoa** [comment]
Fixed in PR: https://github.com/microsoft/Power-Fx/pull/1046
