### ISSUE TITLE
support allOf in parsing argument parameter

### ISSUE THREAD

**Issue by xieofxie** [microsoft/Power-Fx#961]
This line is not implemented yet:

https://github.com/microsoft/Power-Fx/blob/db816eb5a9064584784bfb76ea34cf8c89f3c94e/src/libraries/Microsoft.PowerFx.Connectors/ArgumentMapper.cs#L125

My example is provided internally.

**Comment by LucGenetier** [comment]
https://github.com/microsoft/Power-Fx/pull/1112
