### ISSUE TITLE
Unexpected error when running 0.2.1 on multiple threads 

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/Power-Fx#974]
In my project there is an automated test that covers the integration with Power-Fx. One of the tests is very simple - it evaluates the following expression: `(12 + 5) * 2`. However, sometimes randomly this test would fail with the following exception:

```
System.InvalidOperationException: Errors: Error 0-7: Name isn't valid. This identifier isn't recognized.
Error 7-16: Invalid use of '.'
Error 16-56: Invalid use of '.'
   at Microsoft.PowerFx.Core.Public.CheckResult.ThrowOnErrors()
   at Microsoft.PowerFx.RecalcEngine.Eval(String expressionText, RecordValue parameters)
```

I am using `0.2.1-preview` versions of the `Microsoft.PowerFx.Core` and `Microsoft.PowerFx.Interpreter` packages.

**Comment by MikeStall** [comment]
0.2.1-preview is very old... can you update to 0.2.3?

Are you doing any multi-threaded execution? An any non-english cultures?

**Comment by TonyTroeff** [comment]
Yes, the execution is multithreaded

**Comment by MikeStall** [comment]
0.2.1 was only single threaded - particularly the lexer was not thread safe. 
You'll need to upgrade to at least 0.2.3.

**Comment by TonyTroeff** [comment]
I can validate that after upgrading to `0.2.3-preview` I cannot reproduce this problem.
